spring:
  datasource:
    url: jdbc:mysql://47.96.228.9:3306/crm?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: "!Mysql2020"
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filter: stat
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.study.pojo
server:
  port: 8084
