package com.study.model.mdao;

import com.study.pojo.Acharge;
import java.util.List;

public interface AchargeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acharge
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer acid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acharge
     *
     * @mbg.generated
     */
    int insert(Acharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acharge
     *
     * @mbg.generated
     */
    Acharge selectByPrimaryKey(Integer acid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acharge
     *
     * @mbg.generated
     */
    List<Acharge> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acharge
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Acharge record);
}