package com.study.model.mdao;

import com.study.pojo.Advance;
import java.util.List;

public interface AdvanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advance
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer inid2);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advance
     *
     * @mbg.generated
     */
    int insert(Advance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advance
     *
     * @mbg.generated
     */
    Advance selectByPrimaryKey(Integer inid2);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advance
     *
     * @mbg.generated
     */
    List<Advance> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advance
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Advance record);
}