package com.study.model.mdao;

import com.study.pojo.Baoxian;
import java.util.List;

public interface BaoxianMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baoxian
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer bxid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baoxian
     *
     * @mbg.generated
     */
    int insert(Baoxian record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baoxian
     *
     * @mbg.generated
     */
    Baoxian selectByPrimaryKey(Integer bxid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baoxian
     *
     * @mbg.generated
     */
    List<Baoxian> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baoxian
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Baoxian record);
}