package com.study.model.mdao;

import com.study.pojo.Buwei;
import java.util.List;

public interface BuweiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buwei
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer bwid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buwei
     *
     * @mbg.generated
     */
    int insert(Buwei record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buwei
     *
     * @mbg.generated
     */
    Buwei selectByPrimaryKey(Integer bwid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buwei
     *
     * @mbg.generated
     */
    List<Buwei> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buwei
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Buwei record);
}