package com.study.model.mdao;

import com.study.pojo.Bxjs;
import java.util.List;

public interface BxjsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bxjs
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer reid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bxjs
     *
     * @mbg.generated
     */
    int insert(Bxjs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bxjs
     *
     * @mbg.generated
     */
    Bxjs selectByPrimaryKey(Integer reid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bxjs
     *
     * @mbg.generated
     */
    List<Bxjs> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bxjs
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Bxjs record);
}