package com.study.model.mdao;

import com.study.pojo.Cangku;
import java.util.List;

public interface CangkuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cangku
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer ckid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cangku
     *
     * @mbg.generated
     */
    int insert(Cangku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cangku
     *
     * @mbg.generated
     */
    Cangku selectByPrimaryKey(Integer ckid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cangku
     *
     * @mbg.generated
     */
    List<Cangku> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cangku
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Cangku record);
}