package com.study.model.mdao;

import com.study.pojo.Carmodel;
import java.util.List;

public interface CarmodelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carmodel
     *
     * @mbg.generated
     */
    int insert(Carmodel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carmodel
     *
     * @mbg.generated
     */
    List<Carmodel> selectAll();
}