package com.study.model.mdao;

import com.study.pojo.Carseries;
import java.util.List;

public interface CarseriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carseries
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer seriesid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carseries
     *
     * @mbg.generated
     */
    int insert(Carseries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carseries
     *
     * @mbg.generated
     */
    Carseries selectByPrimaryKey(Integer seriesid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carseries
     *
     * @mbg.generated
     */
    List<Carseries> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carseries
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Carseries record);
}