package com.study.model.mdao;

import com.study.pojo.Carwash;
import java.util.List;

public interface CarwashMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carwash
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carwash
     *
     * @mbg.generated
     */
    int insert(Carwash record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carwash
     *
     * @mbg.generated
     */
    Carwash selectByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carwash
     *
     * @mbg.generated
     */
    List<Carwash> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carwash
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Carwash record);
}