package com.study.model.mdao;

import com.study.pojo.Cgorder;
import java.util.List;

public interface CgorderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgorder
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer cgid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgorder
     *
     * @mbg.generated
     */
    int insert(Cgorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgorder
     *
     * @mbg.generated
     */
    Cgorder selectByPrimaryKey(Integer cgid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgorder
     *
     * @mbg.generated
     */
    List<Cgorder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgorder
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Cgorder record);
}