package com.study.model.mdao;

import com.study.pojo.Cgrk;
import java.util.List;

public interface CgrkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgrk
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer kid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgrk
     *
     * @mbg.generated
     */
    int insert(Cgrk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgrk
     *
     * @mbg.generated
     */
    Cgrk selectByPrimaryKey(Integer kid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgrk
     *
     * @mbg.generated
     */
    List<Cgrk> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgrk
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Cgrk record);
}