package com.study.model.mdao;

import com.study.pojo.Cgth;
import java.util.List;

public interface CgthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgth
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgth
     *
     * @mbg.generated
     */
    int insert(Cgth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgth
     *
     * @mbg.generated
     */
    Cgth selectByPrimaryKey(Integer tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgth
     *
     * @mbg.generated
     */
    List<Cgth> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgth
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Cgth record);
}