package com.study.model.mdao;

import com.study.pojo.Ckfenlei;
import java.util.List;

public interface CkfenleiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ckfenlei
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer ckflid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ckfenlei
     *
     * @mbg.generated
     */
    int insert(Ckfenlei record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ckfenlei
     *
     * @mbg.generated
     */
    Ckfenlei selectByPrimaryKey(Integer ckflid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ckfenlei
     *
     * @mbg.generated
     */
    List<Ckfenlei> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ckfenlei
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Ckfenlei record);
}