package com.study.model.mdao;

import com.study.pojo.Clbx;
import java.util.List;

public interface ClbxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clbx
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer cbxid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clbx
     *
     * @mbg.generated
     */
    int insert(Clbx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clbx
     *
     * @mbg.generated
     */
    Clbx selectByPrimaryKey(Integer cbxid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clbx
     *
     * @mbg.generated
     */
    List<Clbx> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clbx
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Clbx record);
}