package com.study.model.mdao;

import com.study.pojo.Dbfuwu;
import java.util.List;

public interface DbfuwuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbfuwu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer dfid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbfuwu
     *
     * @mbg.generated
     */
    int insert(Dbfuwu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbfuwu
     *
     * @mbg.generated
     */
    Dbfuwu selectByPrimaryKey(Integer dfid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbfuwu
     *
     * @mbg.generated
     */
    List<Dbfuwu> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbfuwu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Dbfuwu record);
}