package com.study.model.mdao;

import com.study.pojo.Debitnote;
import java.util.List;

public interface DebitnoteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debitnote
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer dnid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debitnote
     *
     * @mbg.generated
     */
    int insert(Debitnote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debitnote
     *
     * @mbg.generated
     */
    Debitnote selectByPrimaryKey(Integer dnid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debitnote
     *
     * @mbg.generated
     */
    List<Debitnote> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debitnote
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Debitnote record);
}