package com.study.model.mdao;

import com.study.pojo.Fwleibie;
import java.util.List;

public interface FwleibieMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwleibie
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer fwflid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwleibie
     *
     * @mbg.generated
     */
    int insert(Fwleibie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwleibie
     *
     * @mbg.generated
     */
    Fwleibie selectByPrimaryKey(Integer fwflid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwleibie
     *
     * @mbg.generated
     */
    List<Fwleibie> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwleibie
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Fwleibie record);
}