package com.study.model.mdao;

import com.study.pojo.Gongsi;
import java.util.List;

public interface GongsiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongsi
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer gsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongsi
     *
     * @mbg.generated
     */
    int insert(Gongsi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongsi
     *
     * @mbg.generated
     */
    Gongsi selectByPrimaryKey(Integer gsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongsi
     *
     * @mbg.generated
     */
    List<Gongsi> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongsi
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Gongsi record);
}