package com.study.model.mdao;

import com.study.pojo.Invoice;
import java.util.List;

public interface InvoiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer inid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice
     *
     * @mbg.generated
     */
    int insert(Invoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice
     *
     * @mbg.generated
     */
    Invoice selectByPrimaryKey(Integer inid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice
     *
     * @mbg.generated
     */
    List<Invoice> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Invoice record);
}