package com.study.model.mdao;

import com.study.pojo.Maintenanceitems;
import java.util.List;

public interface MaintenanceitemsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maintenanceitems
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maintenanceitems
     *
     * @mbg.generated
     */
    int insert(Maintenanceitems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maintenanceitems
     *
     * @mbg.generated
     */
    Maintenanceitems selectByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maintenanceitems
     *
     * @mbg.generated
     */
    List<Maintenanceitems> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maintenanceitems
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Maintenanceitems record);
}