package com.study.model.mdao;

import com.study.pojo.Pinpai;
import java.util.List;

public interface PinpaiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pinpai
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer ppid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pinpai
     *
     * @mbg.generated
     */
    int insert(Pinpai record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pinpai
     *
     * @mbg.generated
     */
    Pinpai selectByPrimaryKey(Integer ppid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pinpai
     *
     * @mbg.generated
     */
    List<Pinpai> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pinpai
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Pinpai record);
}