package com.study.model.mdao;

import com.study.pojo.Serviceitems;
import java.util.List;

public interface ServiceitemsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serviceitems
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serviceitems
     *
     * @mbg.generated
     */
    int insert(Serviceitems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serviceitems
     *
     * @mbg.generated
     */
    Serviceitems selectByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serviceitems
     *
     * @mbg.generated
     */
    List<Serviceitems> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serviceitems
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Serviceitems record);
}