package com.study.model.mdao;

import com.study.pojo.Units;
import java.util.List;

public interface UnitsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table units
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer jlid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table units
     *
     * @mbg.generated
     */
    int insert(Units record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table units
     *
     * @mbg.generated
     */
    Units selectByPrimaryKey(Integer jlid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table units
     *
     * @mbg.generated
     */
    List<Units> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table units
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Units record);
}