package com.study.model.mdao;

import com.study.pojo.Ypxs;
import java.util.List;

public interface YpxsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ypxs
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer xsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ypxs
     *
     * @mbg.generated
     */
    int insert(Ypxs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ypxs
     *
     * @mbg.generated
     */
    Ypxs selectByPrimaryKey(Integer xsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ypxs
     *
     * @mbg.generated
     */
    List<Ypxs> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ypxs
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Ypxs record);
}