package com.study.pojo;

import java.io.Serializable;
import java.util.Date;

public class Advance implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advance.inid2
     *
     * @mbg.generated
     */
    private Integer inid2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advance.cusid
     *
     * @mbg.generated
     */
    private Integer cusid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advance.avtime
     *
     * @mbg.generated
     */
    private Date avtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advance.avuser
     *
     * @mbg.generated
     */
    private String avuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advance.avremarks
     *
     * @mbg.generated
     */
    private String avremarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table advance
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advance.inid2
     *
     * @return the value of advance.inid2
     *
     * @mbg.generated
     */
    public Integer getInid2() {
        return inid2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advance.inid2
     *
     * @param inid2 the value for advance.inid2
     *
     * @mbg.generated
     */
    public void setInid2(Integer inid2) {
        this.inid2 = inid2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advance.cusid
     *
     * @return the value of advance.cusid
     *
     * @mbg.generated
     */
    public Integer getCusid() {
        return cusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advance.cusid
     *
     * @param cusid the value for advance.cusid
     *
     * @mbg.generated
     */
    public void setCusid(Integer cusid) {
        this.cusid = cusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advance.avtime
     *
     * @return the value of advance.avtime
     *
     * @mbg.generated
     */
    public Date getAvtime() {
        return avtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advance.avtime
     *
     * @param avtime the value for advance.avtime
     *
     * @mbg.generated
     */
    public void setAvtime(Date avtime) {
        this.avtime = avtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advance.avuser
     *
     * @return the value of advance.avuser
     *
     * @mbg.generated
     */
    public String getAvuser() {
        return avuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advance.avuser
     *
     * @param avuser the value for advance.avuser
     *
     * @mbg.generated
     */
    public void setAvuser(String avuser) {
        this.avuser = avuser == null ? null : avuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advance.avremarks
     *
     * @return the value of advance.avremarks
     *
     * @mbg.generated
     */
    public String getAvremarks() {
        return avremarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advance.avremarks
     *
     * @param avremarks the value for advance.avremarks
     *
     * @mbg.generated
     */
    public void setAvremarks(String avremarks) {
        this.avremarks = avremarks == null ? null : avremarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advance
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", inid2=").append(inid2);
        sb.append(", cusid=").append(cusid);
        sb.append(", avtime=").append(avtime);
        sb.append(", avuser=").append(avuser);
        sb.append(", avremarks=").append(avremarks);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}