package com.study.pojo;

import java.io.Serializable;

public class Buwei implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buwei.bwid
     *
     * @mbg.generated
     */
    private Integer bwid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buwei.bwname
     *
     * @mbg.generated
     */
    private String bwname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buwei.bwstart
     *
     * @mbg.generated
     */
    private String bwstart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table buwei
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buwei.bwid
     *
     * @return the value of buwei.bwid
     *
     * @mbg.generated
     */
    public Integer getBwid() {
        return bwid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buwei.bwid
     *
     * @param bwid the value for buwei.bwid
     *
     * @mbg.generated
     */
    public void setBwid(Integer bwid) {
        this.bwid = bwid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buwei.bwname
     *
     * @return the value of buwei.bwname
     *
     * @mbg.generated
     */
    public String getBwname() {
        return bwname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buwei.bwname
     *
     * @param bwname the value for buwei.bwname
     *
     * @mbg.generated
     */
    public void setBwname(String bwname) {
        this.bwname = bwname == null ? null : bwname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buwei.bwstart
     *
     * @return the value of buwei.bwstart
     *
     * @mbg.generated
     */
    public String getBwstart() {
        return bwstart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buwei.bwstart
     *
     * @param bwstart the value for buwei.bwstart
     *
     * @mbg.generated
     */
    public void setBwstart(String bwstart) {
        this.bwstart = bwstart == null ? null : bwstart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buwei
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", bwid=").append(bwid);
        sb.append(", bwname=").append(bwname);
        sb.append(", bwstart=").append(bwstart);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}