package com.study.pojo;

import java.io.Serializable;
import java.util.Date;

public class Bxjs implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bxjs.reid
     *
     * @mbg.generated
     */
    private Integer reid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bxjs.empno
     *
     * @mbg.generated
     */
    private Integer empno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bxjs.cusid
     *
     * @mbg.generated
     */
    private Integer cusid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bxjs.coid
     *
     * @mbg.generated
     */
    private Integer coid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bxjs.rid
     *
     * @mbg.generated
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bxjs.redh
     *
     * @mbg.generated
     */
    private String redh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bxjs.restate
     *
     * @mbg.generated
     */
    private String restate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bxjs.redate
     *
     * @mbg.generated
     */
    private Date redate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bxjs
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bxjs.reid
     *
     * @return the value of bxjs.reid
     *
     * @mbg.generated
     */
    public Integer getReid() {
        return reid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bxjs.reid
     *
     * @param reid the value for bxjs.reid
     *
     * @mbg.generated
     */
    public void setReid(Integer reid) {
        this.reid = reid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bxjs.empno
     *
     * @return the value of bxjs.empno
     *
     * @mbg.generated
     */
    public Integer getEmpno() {
        return empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bxjs.empno
     *
     * @param empno the value for bxjs.empno
     *
     * @mbg.generated
     */
    public void setEmpno(Integer empno) {
        this.empno = empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bxjs.cusid
     *
     * @return the value of bxjs.cusid
     *
     * @mbg.generated
     */
    public Integer getCusid() {
        return cusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bxjs.cusid
     *
     * @param cusid the value for bxjs.cusid
     *
     * @mbg.generated
     */
    public void setCusid(Integer cusid) {
        this.cusid = cusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bxjs.coid
     *
     * @return the value of bxjs.coid
     *
     * @mbg.generated
     */
    public Integer getCoid() {
        return coid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bxjs.coid
     *
     * @param coid the value for bxjs.coid
     *
     * @mbg.generated
     */
    public void setCoid(Integer coid) {
        this.coid = coid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bxjs.rid
     *
     * @return the value of bxjs.rid
     *
     * @mbg.generated
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bxjs.rid
     *
     * @param rid the value for bxjs.rid
     *
     * @mbg.generated
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bxjs.redh
     *
     * @return the value of bxjs.redh
     *
     * @mbg.generated
     */
    public String getRedh() {
        return redh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bxjs.redh
     *
     * @param redh the value for bxjs.redh
     *
     * @mbg.generated
     */
    public void setRedh(String redh) {
        this.redh = redh == null ? null : redh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bxjs.restate
     *
     * @return the value of bxjs.restate
     *
     * @mbg.generated
     */
    public String getRestate() {
        return restate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bxjs.restate
     *
     * @param restate the value for bxjs.restate
     *
     * @mbg.generated
     */
    public void setRestate(String restate) {
        this.restate = restate == null ? null : restate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bxjs.redate
     *
     * @return the value of bxjs.redate
     *
     * @mbg.generated
     */
    public Date getRedate() {
        return redate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bxjs.redate
     *
     * @param redate the value for bxjs.redate
     *
     * @mbg.generated
     */
    public void setRedate(Date redate) {
        this.redate = redate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bxjs
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", reid=").append(reid);
        sb.append(", empno=").append(empno);
        sb.append(", cusid=").append(cusid);
        sb.append(", coid=").append(coid);
        sb.append(", rid=").append(rid);
        sb.append(", redh=").append(redh);
        sb.append(", restate=").append(restate);
        sb.append(", redate=").append(redate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}