package com.study.pojo;

import java.io.Serializable;

public class Cangku implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cangku.ckid
     *
     * @mbg.generated
     */
    private Integer ckid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cangku.ppid
     *
     * @mbg.generated
     */
    private Integer ppid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cangku.ckflid
     *
     * @mbg.generated
     */
    private String ckflid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cangku.jlid
     *
     * @mbg.generated
     */
    private Integer jlid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cangku.ckcoding
     *
     * @mbg.generated
     */
    private String ckcoding;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cangku.ckname
     *
     * @mbg.generated
     */
    private String ckname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cangku.inventory
     *
     * @mbg.generated
     */
    private Integer inventory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cangku.yujing
     *
     * @mbg.generated
     */
    private Integer yujing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cangku.jiage1
     *
     * @mbg.generated
     */
    private Float jiage1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cangku.jiage2
     *
     * @mbg.generated
     */
    private Float jiage2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cangku.part
     *
     * @mbg.generated
     */
    private String part;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cangku.guige
     *
     * @mbg.generated
     */
    private String guige;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cangku.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cangku.start
     *
     * @mbg.generated
     */
    private String start;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cangku
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cangku.ckid
     *
     * @return the value of cangku.ckid
     *
     * @mbg.generated
     */
    public Integer getCkid() {
        return ckid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cangku.ckid
     *
     * @param ckid the value for cangku.ckid
     *
     * @mbg.generated
     */
    public void setCkid(Integer ckid) {
        this.ckid = ckid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cangku.ppid
     *
     * @return the value of cangku.ppid
     *
     * @mbg.generated
     */
    public Integer getPpid() {
        return ppid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cangku.ppid
     *
     * @param ppid the value for cangku.ppid
     *
     * @mbg.generated
     */
    public void setPpid(Integer ppid) {
        this.ppid = ppid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cangku.ckflid
     *
     * @return the value of cangku.ckflid
     *
     * @mbg.generated
     */
    public String getCkflid() {
        return ckflid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cangku.ckflid
     *
     * @param ckflid the value for cangku.ckflid
     *
     * @mbg.generated
     */
    public void setCkflid(String ckflid) {
        this.ckflid = ckflid == null ? null : ckflid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cangku.jlid
     *
     * @return the value of cangku.jlid
     *
     * @mbg.generated
     */
    public Integer getJlid() {
        return jlid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cangku.jlid
     *
     * @param jlid the value for cangku.jlid
     *
     * @mbg.generated
     */
    public void setJlid(Integer jlid) {
        this.jlid = jlid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cangku.ckcoding
     *
     * @return the value of cangku.ckcoding
     *
     * @mbg.generated
     */
    public String getCkcoding() {
        return ckcoding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cangku.ckcoding
     *
     * @param ckcoding the value for cangku.ckcoding
     *
     * @mbg.generated
     */
    public void setCkcoding(String ckcoding) {
        this.ckcoding = ckcoding == null ? null : ckcoding.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cangku.ckname
     *
     * @return the value of cangku.ckname
     *
     * @mbg.generated
     */
    public String getCkname() {
        return ckname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cangku.ckname
     *
     * @param ckname the value for cangku.ckname
     *
     * @mbg.generated
     */
    public void setCkname(String ckname) {
        this.ckname = ckname == null ? null : ckname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cangku.inventory
     *
     * @return the value of cangku.inventory
     *
     * @mbg.generated
     */
    public Integer getInventory() {
        return inventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cangku.inventory
     *
     * @param inventory the value for cangku.inventory
     *
     * @mbg.generated
     */
    public void setInventory(Integer inventory) {
        this.inventory = inventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cangku.yujing
     *
     * @return the value of cangku.yujing
     *
     * @mbg.generated
     */
    public Integer getYujing() {
        return yujing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cangku.yujing
     *
     * @param yujing the value for cangku.yujing
     *
     * @mbg.generated
     */
    public void setYujing(Integer yujing) {
        this.yujing = yujing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cangku.jiage1
     *
     * @return the value of cangku.jiage1
     *
     * @mbg.generated
     */
    public Float getJiage1() {
        return jiage1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cangku.jiage1
     *
     * @param jiage1 the value for cangku.jiage1
     *
     * @mbg.generated
     */
    public void setJiage1(Float jiage1) {
        this.jiage1 = jiage1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cangku.jiage2
     *
     * @return the value of cangku.jiage2
     *
     * @mbg.generated
     */
    public Float getJiage2() {
        return jiage2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cangku.jiage2
     *
     * @param jiage2 the value for cangku.jiage2
     *
     * @mbg.generated
     */
    public void setJiage2(Float jiage2) {
        this.jiage2 = jiage2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cangku.part
     *
     * @return the value of cangku.part
     *
     * @mbg.generated
     */
    public String getPart() {
        return part;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cangku.part
     *
     * @param part the value for cangku.part
     *
     * @mbg.generated
     */
    public void setPart(String part) {
        this.part = part == null ? null : part.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cangku.guige
     *
     * @return the value of cangku.guige
     *
     * @mbg.generated
     */
    public String getGuige() {
        return guige;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cangku.guige
     *
     * @param guige the value for cangku.guige
     *
     * @mbg.generated
     */
    public void setGuige(String guige) {
        this.guige = guige == null ? null : guige.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cangku.type
     *
     * @return the value of cangku.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cangku.type
     *
     * @param type the value for cangku.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cangku.start
     *
     * @return the value of cangku.start
     *
     * @mbg.generated
     */
    public String getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cangku.start
     *
     * @param start the value for cangku.start
     *
     * @mbg.generated
     */
    public void setStart(String start) {
        this.start = start == null ? null : start.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cangku
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ckid=").append(ckid);
        sb.append(", ppid=").append(ppid);
        sb.append(", ckflid=").append(ckflid);
        sb.append(", jlid=").append(jlid);
        sb.append(", ckcoding=").append(ckcoding);
        sb.append(", ckname=").append(ckname);
        sb.append(", inventory=").append(inventory);
        sb.append(", yujing=").append(yujing);
        sb.append(", jiage1=").append(jiage1);
        sb.append(", jiage2=").append(jiage2);
        sb.append(", part=").append(part);
        sb.append(", guige=").append(guige);
        sb.append(", type=").append(type);
        sb.append(", start=").append(start);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}