package com.study.pojo;

import java.io.Serializable;
import java.util.Date;

public class Car implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.carid
     *
     * @mbg.generated
     */
    private Integer carid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.brandid
     *
     * @mbg.generated
     */
    private Integer brandid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.seriesid
     *
     * @mbg.generated
     */
    private Integer seriesid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.cusid
     *
     * @mbg.generated
     */
    private Integer cusid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.cus_cusid
     *
     * @mbg.generated
     */
    private Integer cusCusid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.cus
     *
     * @mbg.generated
     */
    private Integer cus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.ccarno
     *
     * @mbg.generated
     */
    private String ccarno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.cbrand
     *
     * @mbg.generated
     */
    private Integer cbrand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.cseries
     *
     * @mbg.generated
     */
    private Integer cseries;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.ccolor
     *
     * @mbg.generated
     */
    private String ccolor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.cduedate
     *
     * @mbg.generated
     */
    private Date cduedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.cyearduedate
     *
     * @mbg.generated
     */
    private Date cyearduedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.cnext
     *
     * @mbg.generated
     */
    private Date cnext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.cnextmile
     *
     * @mbg.generated
     */
    private String cnextmile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.carstatus
     *
     * @mbg.generated
     */
    private Integer carstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table car
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.carid
     *
     * @return the value of car.carid
     *
     * @mbg.generated
     */
    public Integer getCarid() {
        return carid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.carid
     *
     * @param carid the value for car.carid
     *
     * @mbg.generated
     */
    public void setCarid(Integer carid) {
        this.carid = carid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.brandid
     *
     * @return the value of car.brandid
     *
     * @mbg.generated
     */
    public Integer getBrandid() {
        return brandid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.brandid
     *
     * @param brandid the value for car.brandid
     *
     * @mbg.generated
     */
    public void setBrandid(Integer brandid) {
        this.brandid = brandid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.seriesid
     *
     * @return the value of car.seriesid
     *
     * @mbg.generated
     */
    public Integer getSeriesid() {
        return seriesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.seriesid
     *
     * @param seriesid the value for car.seriesid
     *
     * @mbg.generated
     */
    public void setSeriesid(Integer seriesid) {
        this.seriesid = seriesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.cusid
     *
     * @return the value of car.cusid
     *
     * @mbg.generated
     */
    public Integer getCusid() {
        return cusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.cusid
     *
     * @param cusid the value for car.cusid
     *
     * @mbg.generated
     */
    public void setCusid(Integer cusid) {
        this.cusid = cusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.cus_cusid
     *
     * @return the value of car.cus_cusid
     *
     * @mbg.generated
     */
    public Integer getCusCusid() {
        return cusCusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.cus_cusid
     *
     * @param cusCusid the value for car.cus_cusid
     *
     * @mbg.generated
     */
    public void setCusCusid(Integer cusCusid) {
        this.cusCusid = cusCusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.cus
     *
     * @return the value of car.cus
     *
     * @mbg.generated
     */
    public Integer getCus() {
        return cus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.cus
     *
     * @param cus the value for car.cus
     *
     * @mbg.generated
     */
    public void setCus(Integer cus) {
        this.cus = cus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.ccarno
     *
     * @return the value of car.ccarno
     *
     * @mbg.generated
     */
    public String getCcarno() {
        return ccarno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.ccarno
     *
     * @param ccarno the value for car.ccarno
     *
     * @mbg.generated
     */
    public void setCcarno(String ccarno) {
        this.ccarno = ccarno == null ? null : ccarno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.cbrand
     *
     * @return the value of car.cbrand
     *
     * @mbg.generated
     */
    public Integer getCbrand() {
        return cbrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.cbrand
     *
     * @param cbrand the value for car.cbrand
     *
     * @mbg.generated
     */
    public void setCbrand(Integer cbrand) {
        this.cbrand = cbrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.cseries
     *
     * @return the value of car.cseries
     *
     * @mbg.generated
     */
    public Integer getCseries() {
        return cseries;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.cseries
     *
     * @param cseries the value for car.cseries
     *
     * @mbg.generated
     */
    public void setCseries(Integer cseries) {
        this.cseries = cseries;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.ccolor
     *
     * @return the value of car.ccolor
     *
     * @mbg.generated
     */
    public String getCcolor() {
        return ccolor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.ccolor
     *
     * @param ccolor the value for car.ccolor
     *
     * @mbg.generated
     */
    public void setCcolor(String ccolor) {
        this.ccolor = ccolor == null ? null : ccolor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.cduedate
     *
     * @return the value of car.cduedate
     *
     * @mbg.generated
     */
    public Date getCduedate() {
        return cduedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.cduedate
     *
     * @param cduedate the value for car.cduedate
     *
     * @mbg.generated
     */
    public void setCduedate(Date cduedate) {
        this.cduedate = cduedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.cyearduedate
     *
     * @return the value of car.cyearduedate
     *
     * @mbg.generated
     */
    public Date getCyearduedate() {
        return cyearduedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.cyearduedate
     *
     * @param cyearduedate the value for car.cyearduedate
     *
     * @mbg.generated
     */
    public void setCyearduedate(Date cyearduedate) {
        this.cyearduedate = cyearduedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.cnext
     *
     * @return the value of car.cnext
     *
     * @mbg.generated
     */
    public Date getCnext() {
        return cnext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.cnext
     *
     * @param cnext the value for car.cnext
     *
     * @mbg.generated
     */
    public void setCnext(Date cnext) {
        this.cnext = cnext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.cnextmile
     *
     * @return the value of car.cnextmile
     *
     * @mbg.generated
     */
    public String getCnextmile() {
        return cnextmile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.cnextmile
     *
     * @param cnextmile the value for car.cnextmile
     *
     * @mbg.generated
     */
    public void setCnextmile(String cnextmile) {
        this.cnextmile = cnextmile == null ? null : cnextmile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.carstatus
     *
     * @return the value of car.carstatus
     *
     * @mbg.generated
     */
    public Integer getCarstatus() {
        return carstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.carstatus
     *
     * @param carstatus the value for car.carstatus
     *
     * @mbg.generated
     */
    public void setCarstatus(Integer carstatus) {
        this.carstatus = carstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", carid=").append(carid);
        sb.append(", brandid=").append(brandid);
        sb.append(", seriesid=").append(seriesid);
        sb.append(", cusid=").append(cusid);
        sb.append(", cusCusid=").append(cusCusid);
        sb.append(", cus=").append(cus);
        sb.append(", ccarno=").append(ccarno);
        sb.append(", cbrand=").append(cbrand);
        sb.append(", cseries=").append(cseries);
        sb.append(", ccolor=").append(ccolor);
        sb.append(", cduedate=").append(cduedate);
        sb.append(", cyearduedate=").append(cyearduedate);
        sb.append(", cnext=").append(cnext);
        sb.append(", cnextmile=").append(cnextmile);
        sb.append(", carstatus=").append(carstatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}