package com.study.pojo;

import java.io.Serializable;

public class Carbrand implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carbrand.brandid
     *
     * @mbg.generated
     */
    private Integer brandid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carbrand.storeid
     *
     * @mbg.generated
     */
    private Integer storeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carbrand.brandstore
     *
     * @mbg.generated
     */
    private Integer brandstore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carbrand.brandname
     *
     * @mbg.generated
     */
    private String brandname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carbrand.brandengname
     *
     * @mbg.generated
     */
    private String brandengname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carbrand.brandremark
     *
     * @mbg.generated
     */
    private String brandremark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carbrand.brandstatus
     *
     * @mbg.generated
     */
    private Integer brandstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table carbrand
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carbrand.brandid
     *
     * @return the value of carbrand.brandid
     *
     * @mbg.generated
     */
    public Integer getBrandid() {
        return brandid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carbrand.brandid
     *
     * @param brandid the value for carbrand.brandid
     *
     * @mbg.generated
     */
    public void setBrandid(Integer brandid) {
        this.brandid = brandid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carbrand.storeid
     *
     * @return the value of carbrand.storeid
     *
     * @mbg.generated
     */
    public Integer getStoreid() {
        return storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carbrand.storeid
     *
     * @param storeid the value for carbrand.storeid
     *
     * @mbg.generated
     */
    public void setStoreid(Integer storeid) {
        this.storeid = storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carbrand.brandstore
     *
     * @return the value of carbrand.brandstore
     *
     * @mbg.generated
     */
    public Integer getBrandstore() {
        return brandstore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carbrand.brandstore
     *
     * @param brandstore the value for carbrand.brandstore
     *
     * @mbg.generated
     */
    public void setBrandstore(Integer brandstore) {
        this.brandstore = brandstore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carbrand.brandname
     *
     * @return the value of carbrand.brandname
     *
     * @mbg.generated
     */
    public String getBrandname() {
        return brandname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carbrand.brandname
     *
     * @param brandname the value for carbrand.brandname
     *
     * @mbg.generated
     */
    public void setBrandname(String brandname) {
        this.brandname = brandname == null ? null : brandname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carbrand.brandengname
     *
     * @return the value of carbrand.brandengname
     *
     * @mbg.generated
     */
    public String getBrandengname() {
        return brandengname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carbrand.brandengname
     *
     * @param brandengname the value for carbrand.brandengname
     *
     * @mbg.generated
     */
    public void setBrandengname(String brandengname) {
        this.brandengname = brandengname == null ? null : brandengname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carbrand.brandremark
     *
     * @return the value of carbrand.brandremark
     *
     * @mbg.generated
     */
    public String getBrandremark() {
        return brandremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carbrand.brandremark
     *
     * @param brandremark the value for carbrand.brandremark
     *
     * @mbg.generated
     */
    public void setBrandremark(String brandremark) {
        this.brandremark = brandremark == null ? null : brandremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carbrand.brandstatus
     *
     * @return the value of carbrand.brandstatus
     *
     * @mbg.generated
     */
    public Integer getBrandstatus() {
        return brandstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carbrand.brandstatus
     *
     * @param brandstatus the value for carbrand.brandstatus
     *
     * @mbg.generated
     */
    public void setBrandstatus(Integer brandstatus) {
        this.brandstatus = brandstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carbrand
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", brandid=").append(brandid);
        sb.append(", storeid=").append(storeid);
        sb.append(", brandstore=").append(brandstore);
        sb.append(", brandname=").append(brandname);
        sb.append(", brandengname=").append(brandengname);
        sb.append(", brandremark=").append(brandremark);
        sb.append(", brandstatus=").append(brandstatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}