package com.study.pojo;

import java.io.Serializable;

public class Carmodel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carmodel.modelid
     *
     * @mbg.generated
     */
    private Integer modelid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carmodel.modelimg
     *
     * @mbg.generated
     */
    private String modelimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carmodel.modelseries
     *
     * @mbg.generated
     */
    private Integer modelseries;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carmodel.modelengname
     *
     * @mbg.generated
     */
    private String modelengname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carmodel.model
     *
     * @mbg.generated
     */
    private String model;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carmodel.mguideprice
     *
     * @mbg.generated
     */
    private Integer mguideprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carmodel.msaleprice
     *
     * @mbg.generated
     */
    private Integer msaleprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carmodel.mdiscounts
     *
     * @mbg.generated
     */
    private Integer mdiscounts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table carmodel
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carmodel.modelid
     *
     * @return the value of carmodel.modelid
     *
     * @mbg.generated
     */
    public Integer getModelid() {
        return modelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carmodel.modelid
     *
     * @param modelid the value for carmodel.modelid
     *
     * @mbg.generated
     */
    public void setModelid(Integer modelid) {
        this.modelid = modelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carmodel.modelimg
     *
     * @return the value of carmodel.modelimg
     *
     * @mbg.generated
     */
    public String getModelimg() {
        return modelimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carmodel.modelimg
     *
     * @param modelimg the value for carmodel.modelimg
     *
     * @mbg.generated
     */
    public void setModelimg(String modelimg) {
        this.modelimg = modelimg == null ? null : modelimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carmodel.modelseries
     *
     * @return the value of carmodel.modelseries
     *
     * @mbg.generated
     */
    public Integer getModelseries() {
        return modelseries;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carmodel.modelseries
     *
     * @param modelseries the value for carmodel.modelseries
     *
     * @mbg.generated
     */
    public void setModelseries(Integer modelseries) {
        this.modelseries = modelseries;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carmodel.modelengname
     *
     * @return the value of carmodel.modelengname
     *
     * @mbg.generated
     */
    public String getModelengname() {
        return modelengname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carmodel.modelengname
     *
     * @param modelengname the value for carmodel.modelengname
     *
     * @mbg.generated
     */
    public void setModelengname(String modelengname) {
        this.modelengname = modelengname == null ? null : modelengname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carmodel.model
     *
     * @return the value of carmodel.model
     *
     * @mbg.generated
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carmodel.model
     *
     * @param model the value for carmodel.model
     *
     * @mbg.generated
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carmodel.mguideprice
     *
     * @return the value of carmodel.mguideprice
     *
     * @mbg.generated
     */
    public Integer getMguideprice() {
        return mguideprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carmodel.mguideprice
     *
     * @param mguideprice the value for carmodel.mguideprice
     *
     * @mbg.generated
     */
    public void setMguideprice(Integer mguideprice) {
        this.mguideprice = mguideprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carmodel.msaleprice
     *
     * @return the value of carmodel.msaleprice
     *
     * @mbg.generated
     */
    public Integer getMsaleprice() {
        return msaleprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carmodel.msaleprice
     *
     * @param msaleprice the value for carmodel.msaleprice
     *
     * @mbg.generated
     */
    public void setMsaleprice(Integer msaleprice) {
        this.msaleprice = msaleprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carmodel.mdiscounts
     *
     * @return the value of carmodel.mdiscounts
     *
     * @mbg.generated
     */
    public Integer getMdiscounts() {
        return mdiscounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carmodel.mdiscounts
     *
     * @param mdiscounts the value for carmodel.mdiscounts
     *
     * @mbg.generated
     */
    public void setMdiscounts(Integer mdiscounts) {
        this.mdiscounts = mdiscounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carmodel
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", modelid=").append(modelid);
        sb.append(", modelimg=").append(modelimg);
        sb.append(", modelseries=").append(modelseries);
        sb.append(", modelengname=").append(modelengname);
        sb.append(", model=").append(model);
        sb.append(", mguideprice=").append(mguideprice);
        sb.append(", msaleprice=").append(msaleprice);
        sb.append(", mdiscounts=").append(mdiscounts);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}