package com.study.pojo;

import java.io.Serializable;

public class Carseries implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carseries.seriesid
     *
     * @mbg.generated
     */
    private Integer seriesid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carseries.seriesimg
     *
     * @mbg.generated
     */
    private String seriesimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carseries.seriesbrand
     *
     * @mbg.generated
     */
    private Integer seriesbrand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carseries.seriesname
     *
     * @mbg.generated
     */
    private String seriesname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carseries.seriesengname
     *
     * @mbg.generated
     */
    private String seriesengname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carseries.seriestype
     *
     * @mbg.generated
     */
    private String seriestype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carseries.seriesremark
     *
     * @mbg.generated
     */
    private String seriesremark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carseries.seriesstatus
     *
     * @mbg.generated
     */
    private Integer seriesstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table carseries
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carseries.seriesid
     *
     * @return the value of carseries.seriesid
     *
     * @mbg.generated
     */
    public Integer getSeriesid() {
        return seriesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carseries.seriesid
     *
     * @param seriesid the value for carseries.seriesid
     *
     * @mbg.generated
     */
    public void setSeriesid(Integer seriesid) {
        this.seriesid = seriesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carseries.seriesimg
     *
     * @return the value of carseries.seriesimg
     *
     * @mbg.generated
     */
    public String getSeriesimg() {
        return seriesimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carseries.seriesimg
     *
     * @param seriesimg the value for carseries.seriesimg
     *
     * @mbg.generated
     */
    public void setSeriesimg(String seriesimg) {
        this.seriesimg = seriesimg == null ? null : seriesimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carseries.seriesbrand
     *
     * @return the value of carseries.seriesbrand
     *
     * @mbg.generated
     */
    public Integer getSeriesbrand() {
        return seriesbrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carseries.seriesbrand
     *
     * @param seriesbrand the value for carseries.seriesbrand
     *
     * @mbg.generated
     */
    public void setSeriesbrand(Integer seriesbrand) {
        this.seriesbrand = seriesbrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carseries.seriesname
     *
     * @return the value of carseries.seriesname
     *
     * @mbg.generated
     */
    public String getSeriesname() {
        return seriesname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carseries.seriesname
     *
     * @param seriesname the value for carseries.seriesname
     *
     * @mbg.generated
     */
    public void setSeriesname(String seriesname) {
        this.seriesname = seriesname == null ? null : seriesname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carseries.seriesengname
     *
     * @return the value of carseries.seriesengname
     *
     * @mbg.generated
     */
    public String getSeriesengname() {
        return seriesengname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carseries.seriesengname
     *
     * @param seriesengname the value for carseries.seriesengname
     *
     * @mbg.generated
     */
    public void setSeriesengname(String seriesengname) {
        this.seriesengname = seriesengname == null ? null : seriesengname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carseries.seriestype
     *
     * @return the value of carseries.seriestype
     *
     * @mbg.generated
     */
    public String getSeriestype() {
        return seriestype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carseries.seriestype
     *
     * @param seriestype the value for carseries.seriestype
     *
     * @mbg.generated
     */
    public void setSeriestype(String seriestype) {
        this.seriestype = seriestype == null ? null : seriestype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carseries.seriesremark
     *
     * @return the value of carseries.seriesremark
     *
     * @mbg.generated
     */
    public String getSeriesremark() {
        return seriesremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carseries.seriesremark
     *
     * @param seriesremark the value for carseries.seriesremark
     *
     * @mbg.generated
     */
    public void setSeriesremark(String seriesremark) {
        this.seriesremark = seriesremark == null ? null : seriesremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carseries.seriesstatus
     *
     * @return the value of carseries.seriesstatus
     *
     * @mbg.generated
     */
    public Integer getSeriesstatus() {
        return seriesstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carseries.seriesstatus
     *
     * @param seriesstatus the value for carseries.seriesstatus
     *
     * @mbg.generated
     */
    public void setSeriesstatus(Integer seriesstatus) {
        this.seriesstatus = seriesstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carseries
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", seriesid=").append(seriesid);
        sb.append(", seriesimg=").append(seriesimg);
        sb.append(", seriesbrand=").append(seriesbrand);
        sb.append(", seriesname=").append(seriesname);
        sb.append(", seriesengname=").append(seriesengname);
        sb.append(", seriestype=").append(seriestype);
        sb.append(", seriesremark=").append(seriesremark);
        sb.append(", seriesstatus=").append(seriesstatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}