package com.study.pojo;

import java.io.Serializable;
import java.util.Date;

public class Carwash implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carwash.cid
     *
     * @mbg.generated
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carwash.empno
     *
     * @mbg.generated
     */
    private Integer empno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carwash.cusid
     *
     * @mbg.generated
     */
    private Integer cusid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carwash.emp_empno
     *
     * @mbg.generated
     */
    private Integer empEmpno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carwash.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carwash.cnumber
     *
     * @mbg.generated
     */
    private String cnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carwash.cbilltype
     *
     * @mbg.generated
     */
    private String cbilltype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carwash.cdispatchtype
     *
     * @mbg.generated
     */
    private String cdispatchtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carwash.cmoney
     *
     * @mbg.generated
     */
    private Integer cmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table carwash
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carwash.cid
     *
     * @return the value of carwash.cid
     *
     * @mbg.generated
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carwash.cid
     *
     * @param cid the value for carwash.cid
     *
     * @mbg.generated
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carwash.empno
     *
     * @return the value of carwash.empno
     *
     * @mbg.generated
     */
    public Integer getEmpno() {
        return empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carwash.empno
     *
     * @param empno the value for carwash.empno
     *
     * @mbg.generated
     */
    public void setEmpno(Integer empno) {
        this.empno = empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carwash.cusid
     *
     * @return the value of carwash.cusid
     *
     * @mbg.generated
     */
    public Integer getCusid() {
        return cusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carwash.cusid
     *
     * @param cusid the value for carwash.cusid
     *
     * @mbg.generated
     */
    public void setCusid(Integer cusid) {
        this.cusid = cusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carwash.emp_empno
     *
     * @return the value of carwash.emp_empno
     *
     * @mbg.generated
     */
    public Integer getEmpEmpno() {
        return empEmpno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carwash.emp_empno
     *
     * @param empEmpno the value for carwash.emp_empno
     *
     * @mbg.generated
     */
    public void setEmpEmpno(Integer empEmpno) {
        this.empEmpno = empEmpno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carwash.ctime
     *
     * @return the value of carwash.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carwash.ctime
     *
     * @param ctime the value for carwash.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carwash.cnumber
     *
     * @return the value of carwash.cnumber
     *
     * @mbg.generated
     */
    public String getCnumber() {
        return cnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carwash.cnumber
     *
     * @param cnumber the value for carwash.cnumber
     *
     * @mbg.generated
     */
    public void setCnumber(String cnumber) {
        this.cnumber = cnumber == null ? null : cnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carwash.cbilltype
     *
     * @return the value of carwash.cbilltype
     *
     * @mbg.generated
     */
    public String getCbilltype() {
        return cbilltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carwash.cbilltype
     *
     * @param cbilltype the value for carwash.cbilltype
     *
     * @mbg.generated
     */
    public void setCbilltype(String cbilltype) {
        this.cbilltype = cbilltype == null ? null : cbilltype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carwash.cdispatchtype
     *
     * @return the value of carwash.cdispatchtype
     *
     * @mbg.generated
     */
    public String getCdispatchtype() {
        return cdispatchtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carwash.cdispatchtype
     *
     * @param cdispatchtype the value for carwash.cdispatchtype
     *
     * @mbg.generated
     */
    public void setCdispatchtype(String cdispatchtype) {
        this.cdispatchtype = cdispatchtype == null ? null : cdispatchtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carwash.cmoney
     *
     * @return the value of carwash.cmoney
     *
     * @mbg.generated
     */
    public Integer getCmoney() {
        return cmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carwash.cmoney
     *
     * @param cmoney the value for carwash.cmoney
     *
     * @mbg.generated
     */
    public void setCmoney(Integer cmoney) {
        this.cmoney = cmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carwash
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", cid=").append(cid);
        sb.append(", empno=").append(empno);
        sb.append(", cusid=").append(cusid);
        sb.append(", empEmpno=").append(empEmpno);
        sb.append(", ctime=").append(ctime);
        sb.append(", cnumber=").append(cnumber);
        sb.append(", cbilltype=").append(cbilltype);
        sb.append(", cdispatchtype=").append(cdispatchtype);
        sb.append(", cmoney=").append(cmoney);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}