package com.study.pojo;

import java.io.Serializable;
import java.util.Date;

public class Cgorder implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgorder.cgid
     *
     * @mbg.generated
     */
    private Integer cgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgorder.empno
     *
     * @mbg.generated
     */
    private Integer empno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgorder.ckflid
     *
     * @mbg.generated
     */
    private String ckflid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgorder.coid
     *
     * @mbg.generated
     */
    private Integer coid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgorder.sid2
     *
     * @mbg.generated
     */
    private Integer sid2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgorder.cgdanhao
     *
     * @mbg.generated
     */
    private String cgdanhao;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgorder.danjutype
     *
     * @mbg.generated
     */
    private String danjutype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgorder.dhtime
     *
     * @mbg.generated
     */
    private Date dhtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgorder.shtype
     *
     * @mbg.generated
     */
    private String shtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgorder.rktype
     *
     * @mbg.generated
     */
    private String rktype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgorder.cgmoney
     *
     * @mbg.generated
     */
    private Integer cgmoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgorder.ydhtime
     *
     * @mbg.generated
     */
    private Date ydhtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgorder.bz
     *
     * @mbg.generated
     */
    private String bz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgorder.cgfind
     *
     * @mbg.generated
     */
    private String cgfind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cgorder
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgorder.cgid
     *
     * @return the value of cgorder.cgid
     *
     * @mbg.generated
     */
    public Integer getCgid() {
        return cgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgorder.cgid
     *
     * @param cgid the value for cgorder.cgid
     *
     * @mbg.generated
     */
    public void setCgid(Integer cgid) {
        this.cgid = cgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgorder.empno
     *
     * @return the value of cgorder.empno
     *
     * @mbg.generated
     */
    public Integer getEmpno() {
        return empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgorder.empno
     *
     * @param empno the value for cgorder.empno
     *
     * @mbg.generated
     */
    public void setEmpno(Integer empno) {
        this.empno = empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgorder.ckflid
     *
     * @return the value of cgorder.ckflid
     *
     * @mbg.generated
     */
    public String getCkflid() {
        return ckflid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgorder.ckflid
     *
     * @param ckflid the value for cgorder.ckflid
     *
     * @mbg.generated
     */
    public void setCkflid(String ckflid) {
        this.ckflid = ckflid == null ? null : ckflid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgorder.coid
     *
     * @return the value of cgorder.coid
     *
     * @mbg.generated
     */
    public Integer getCoid() {
        return coid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgorder.coid
     *
     * @param coid the value for cgorder.coid
     *
     * @mbg.generated
     */
    public void setCoid(Integer coid) {
        this.coid = coid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgorder.sid2
     *
     * @return the value of cgorder.sid2
     *
     * @mbg.generated
     */
    public Integer getSid2() {
        return sid2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgorder.sid2
     *
     * @param sid2 the value for cgorder.sid2
     *
     * @mbg.generated
     */
    public void setSid2(Integer sid2) {
        this.sid2 = sid2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgorder.cgdanhao
     *
     * @return the value of cgorder.cgdanhao
     *
     * @mbg.generated
     */
    public String getCgdanhao() {
        return cgdanhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgorder.cgdanhao
     *
     * @param cgdanhao the value for cgorder.cgdanhao
     *
     * @mbg.generated
     */
    public void setCgdanhao(String cgdanhao) {
        this.cgdanhao = cgdanhao == null ? null : cgdanhao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgorder.danjutype
     *
     * @return the value of cgorder.danjutype
     *
     * @mbg.generated
     */
    public String getDanjutype() {
        return danjutype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgorder.danjutype
     *
     * @param danjutype the value for cgorder.danjutype
     *
     * @mbg.generated
     */
    public void setDanjutype(String danjutype) {
        this.danjutype = danjutype == null ? null : danjutype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgorder.dhtime
     *
     * @return the value of cgorder.dhtime
     *
     * @mbg.generated
     */
    public Date getDhtime() {
        return dhtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgorder.dhtime
     *
     * @param dhtime the value for cgorder.dhtime
     *
     * @mbg.generated
     */
    public void setDhtime(Date dhtime) {
        this.dhtime = dhtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgorder.shtype
     *
     * @return the value of cgorder.shtype
     *
     * @mbg.generated
     */
    public String getShtype() {
        return shtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgorder.shtype
     *
     * @param shtype the value for cgorder.shtype
     *
     * @mbg.generated
     */
    public void setShtype(String shtype) {
        this.shtype = shtype == null ? null : shtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgorder.rktype
     *
     * @return the value of cgorder.rktype
     *
     * @mbg.generated
     */
    public String getRktype() {
        return rktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgorder.rktype
     *
     * @param rktype the value for cgorder.rktype
     *
     * @mbg.generated
     */
    public void setRktype(String rktype) {
        this.rktype = rktype == null ? null : rktype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgorder.cgmoney
     *
     * @return the value of cgorder.cgmoney
     *
     * @mbg.generated
     */
    public Integer getCgmoney() {
        return cgmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgorder.cgmoney
     *
     * @param cgmoney the value for cgorder.cgmoney
     *
     * @mbg.generated
     */
    public void setCgmoney(Integer cgmoney) {
        this.cgmoney = cgmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgorder.ydhtime
     *
     * @return the value of cgorder.ydhtime
     *
     * @mbg.generated
     */
    public Date getYdhtime() {
        return ydhtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgorder.ydhtime
     *
     * @param ydhtime the value for cgorder.ydhtime
     *
     * @mbg.generated
     */
    public void setYdhtime(Date ydhtime) {
        this.ydhtime = ydhtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgorder.bz
     *
     * @return the value of cgorder.bz
     *
     * @mbg.generated
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgorder.bz
     *
     * @param bz the value for cgorder.bz
     *
     * @mbg.generated
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgorder.cgfind
     *
     * @return the value of cgorder.cgfind
     *
     * @mbg.generated
     */
    public String getCgfind() {
        return cgfind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgorder.cgfind
     *
     * @param cgfind the value for cgorder.cgfind
     *
     * @mbg.generated
     */
    public void setCgfind(String cgfind) {
        this.cgfind = cgfind == null ? null : cgfind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgorder
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", cgid=").append(cgid);
        sb.append(", empno=").append(empno);
        sb.append(", ckflid=").append(ckflid);
        sb.append(", coid=").append(coid);
        sb.append(", sid2=").append(sid2);
        sb.append(", cgdanhao=").append(cgdanhao);
        sb.append(", danjutype=").append(danjutype);
        sb.append(", dhtime=").append(dhtime);
        sb.append(", shtype=").append(shtype);
        sb.append(", rktype=").append(rktype);
        sb.append(", cgmoney=").append(cgmoney);
        sb.append(", ydhtime=").append(ydhtime);
        sb.append(", bz=").append(bz);
        sb.append(", cgfind=").append(cgfind);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}