package com.study.pojo;

import java.io.Serializable;
import java.util.Date;

public class Cgrk implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgrk.kid
     *
     * @mbg.generated
     */
    private Integer kid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgrk.cgid
     *
     * @mbg.generated
     */
    private Integer cgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgrk.rkdh
     *
     * @mbg.generated
     */
    private String rkdh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgrk.kdjtype
     *
     * @mbg.generated
     */
    private String kdjtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgrk.kcgmoney
     *
     * @mbg.generated
     */
    private Integer kcgmoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgrk.rktime
     *
     * @mbg.generated
     */
    private Date rktime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgrk.fpdh
     *
     * @mbg.generated
     */
    private String fpdh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgrk.orderbh
     *
     * @mbg.generated
     */
    private String orderbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgrk.kbz
     *
     * @mbg.generated
     */
    private String kbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cgrk
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgrk.kid
     *
     * @return the value of cgrk.kid
     *
     * @mbg.generated
     */
    public Integer getKid() {
        return kid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgrk.kid
     *
     * @param kid the value for cgrk.kid
     *
     * @mbg.generated
     */
    public void setKid(Integer kid) {
        this.kid = kid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgrk.cgid
     *
     * @return the value of cgrk.cgid
     *
     * @mbg.generated
     */
    public Integer getCgid() {
        return cgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgrk.cgid
     *
     * @param cgid the value for cgrk.cgid
     *
     * @mbg.generated
     */
    public void setCgid(Integer cgid) {
        this.cgid = cgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgrk.rkdh
     *
     * @return the value of cgrk.rkdh
     *
     * @mbg.generated
     */
    public String getRkdh() {
        return rkdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgrk.rkdh
     *
     * @param rkdh the value for cgrk.rkdh
     *
     * @mbg.generated
     */
    public void setRkdh(String rkdh) {
        this.rkdh = rkdh == null ? null : rkdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgrk.kdjtype
     *
     * @return the value of cgrk.kdjtype
     *
     * @mbg.generated
     */
    public String getKdjtype() {
        return kdjtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgrk.kdjtype
     *
     * @param kdjtype the value for cgrk.kdjtype
     *
     * @mbg.generated
     */
    public void setKdjtype(String kdjtype) {
        this.kdjtype = kdjtype == null ? null : kdjtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgrk.kcgmoney
     *
     * @return the value of cgrk.kcgmoney
     *
     * @mbg.generated
     */
    public Integer getKcgmoney() {
        return kcgmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgrk.kcgmoney
     *
     * @param kcgmoney the value for cgrk.kcgmoney
     *
     * @mbg.generated
     */
    public void setKcgmoney(Integer kcgmoney) {
        this.kcgmoney = kcgmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgrk.rktime
     *
     * @return the value of cgrk.rktime
     *
     * @mbg.generated
     */
    public Date getRktime() {
        return rktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgrk.rktime
     *
     * @param rktime the value for cgrk.rktime
     *
     * @mbg.generated
     */
    public void setRktime(Date rktime) {
        this.rktime = rktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgrk.fpdh
     *
     * @return the value of cgrk.fpdh
     *
     * @mbg.generated
     */
    public String getFpdh() {
        return fpdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgrk.fpdh
     *
     * @param fpdh the value for cgrk.fpdh
     *
     * @mbg.generated
     */
    public void setFpdh(String fpdh) {
        this.fpdh = fpdh == null ? null : fpdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgrk.orderbh
     *
     * @return the value of cgrk.orderbh
     *
     * @mbg.generated
     */
    public String getOrderbh() {
        return orderbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgrk.orderbh
     *
     * @param orderbh the value for cgrk.orderbh
     *
     * @mbg.generated
     */
    public void setOrderbh(String orderbh) {
        this.orderbh = orderbh == null ? null : orderbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgrk.kbz
     *
     * @return the value of cgrk.kbz
     *
     * @mbg.generated
     */
    public String getKbz() {
        return kbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgrk.kbz
     *
     * @param kbz the value for cgrk.kbz
     *
     * @mbg.generated
     */
    public void setKbz(String kbz) {
        this.kbz = kbz == null ? null : kbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgrk
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", kid=").append(kid);
        sb.append(", cgid=").append(cgid);
        sb.append(", rkdh=").append(rkdh);
        sb.append(", kdjtype=").append(kdjtype);
        sb.append(", kcgmoney=").append(kcgmoney);
        sb.append(", rktime=").append(rktime);
        sb.append(", fpdh=").append(fpdh);
        sb.append(", orderbh=").append(orderbh);
        sb.append(", kbz=").append(kbz);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}