package com.study.pojo;

import java.io.Serializable;
import java.util.Date;

public class Cgth implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgth.tid
     *
     * @mbg.generated
     */
    private Integer tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgth.cgid
     *
     * @mbg.generated
     */
    private Integer cgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgth.thdanhao
     *
     * @mbg.generated
     */
    private String thdanhao;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgth.tdjtype
     *
     * @mbg.generated
     */
    private String tdjtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgth.thmoney
     *
     * @mbg.generated
     */
    private Integer thmoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgth.cjtime
     *
     * @mbg.generated
     */
    private Date cjtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgth.tbz
     *
     * @mbg.generated
     */
    private String tbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cgth
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgth.tid
     *
     * @return the value of cgth.tid
     *
     * @mbg.generated
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgth.tid
     *
     * @param tid the value for cgth.tid
     *
     * @mbg.generated
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgth.cgid
     *
     * @return the value of cgth.cgid
     *
     * @mbg.generated
     */
    public Integer getCgid() {
        return cgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgth.cgid
     *
     * @param cgid the value for cgth.cgid
     *
     * @mbg.generated
     */
    public void setCgid(Integer cgid) {
        this.cgid = cgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgth.thdanhao
     *
     * @return the value of cgth.thdanhao
     *
     * @mbg.generated
     */
    public String getThdanhao() {
        return thdanhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgth.thdanhao
     *
     * @param thdanhao the value for cgth.thdanhao
     *
     * @mbg.generated
     */
    public void setThdanhao(String thdanhao) {
        this.thdanhao = thdanhao == null ? null : thdanhao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgth.tdjtype
     *
     * @return the value of cgth.tdjtype
     *
     * @mbg.generated
     */
    public String getTdjtype() {
        return tdjtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgth.tdjtype
     *
     * @param tdjtype the value for cgth.tdjtype
     *
     * @mbg.generated
     */
    public void setTdjtype(String tdjtype) {
        this.tdjtype = tdjtype == null ? null : tdjtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgth.thmoney
     *
     * @return the value of cgth.thmoney
     *
     * @mbg.generated
     */
    public Integer getThmoney() {
        return thmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgth.thmoney
     *
     * @param thmoney the value for cgth.thmoney
     *
     * @mbg.generated
     */
    public void setThmoney(Integer thmoney) {
        this.thmoney = thmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgth.cjtime
     *
     * @return the value of cgth.cjtime
     *
     * @mbg.generated
     */
    public Date getCjtime() {
        return cjtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgth.cjtime
     *
     * @param cjtime the value for cgth.cjtime
     *
     * @mbg.generated
     */
    public void setCjtime(Date cjtime) {
        this.cjtime = cjtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgth.tbz
     *
     * @return the value of cgth.tbz
     *
     * @mbg.generated
     */
    public String getTbz() {
        return tbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgth.tbz
     *
     * @param tbz the value for cgth.tbz
     *
     * @mbg.generated
     */
    public void setTbz(String tbz) {
        this.tbz = tbz == null ? null : tbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgth
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", tid=").append(tid);
        sb.append(", cgid=").append(cgid);
        sb.append(", thdanhao=").append(thdanhao);
        sb.append(", tdjtype=").append(tdjtype);
        sb.append(", thmoney=").append(thmoney);
        sb.append(", cjtime=").append(cjtime);
        sb.append(", tbz=").append(tbz);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}