package com.study.pojo;

import java.io.Serializable;

public class Ckfenlei implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ckfenlei.ckflid
     *
     * @mbg.generated
     */
    private Integer ckflid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ckfenlei.flname
     *
     * @mbg.generated
     */
    private String flname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ckfenlei.flstart
     *
     * @mbg.generated
     */
    private String flstart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ckfenlei
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ckfenlei.ckflid
     *
     * @return the value of ckfenlei.ckflid
     *
     * @mbg.generated
     */
    public Integer getCkflid() {
        return ckflid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ckfenlei.ckflid
     *
     * @param ckflid the value for ckfenlei.ckflid
     *
     * @mbg.generated
     */
    public void setCkflid(Integer ckflid) {
        this.ckflid = ckflid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ckfenlei.flname
     *
     * @return the value of ckfenlei.flname
     *
     * @mbg.generated
     */
    public String getFlname() {
        return flname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ckfenlei.flname
     *
     * @param flname the value for ckfenlei.flname
     *
     * @mbg.generated
     */
    public void setFlname(String flname) {
        this.flname = flname == null ? null : flname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ckfenlei.flstart
     *
     * @return the value of ckfenlei.flstart
     *
     * @mbg.generated
     */
    public String getFlstart() {
        return flstart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ckfenlei.flstart
     *
     * @param flstart the value for ckfenlei.flstart
     *
     * @mbg.generated
     */
    public void setFlstart(String flstart) {
        this.flstart = flstart == null ? null : flstart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ckfenlei
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ckflid=").append(ckflid);
        sb.append(", flname=").append(flname);
        sb.append(", flstart=").append(flstart);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}