package com.study.pojo;

import java.io.Serializable;
import java.util.Date;

public class Clbx implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clbx.cbxid
     *
     * @mbg.generated
     */
    private Integer cbxid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clbx.carid
     *
     * @mbg.generated
     */
    private Integer carid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clbx.empno
     *
     * @mbg.generated
     */
    private Integer empno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clbx.gsid
     *
     * @mbg.generated
     */
    private Integer gsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clbx.cusid
     *
     * @mbg.generated
     */
    private Integer cusid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clbx.bxdh
     *
     * @mbg.generated
     */
    private String bxdh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clbx.bxdate
     *
     * @mbg.generated
     */
    private Date bxdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clbx.bxstate
     *
     * @mbg.generated
     */
    private String bxstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clbx.bxnum
     *
     * @mbg.generated
     */
    private Integer bxnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clbx.tbdate
     *
     * @mbg.generated
     */
    private Date tbdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clbx.dbdate
     *
     * @mbg.generated
     */
    private Date dbdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table clbx
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clbx.cbxid
     *
     * @return the value of clbx.cbxid
     *
     * @mbg.generated
     */
    public Integer getCbxid() {
        return cbxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clbx.cbxid
     *
     * @param cbxid the value for clbx.cbxid
     *
     * @mbg.generated
     */
    public void setCbxid(Integer cbxid) {
        this.cbxid = cbxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clbx.carid
     *
     * @return the value of clbx.carid
     *
     * @mbg.generated
     */
    public Integer getCarid() {
        return carid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clbx.carid
     *
     * @param carid the value for clbx.carid
     *
     * @mbg.generated
     */
    public void setCarid(Integer carid) {
        this.carid = carid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clbx.empno
     *
     * @return the value of clbx.empno
     *
     * @mbg.generated
     */
    public Integer getEmpno() {
        return empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clbx.empno
     *
     * @param empno the value for clbx.empno
     *
     * @mbg.generated
     */
    public void setEmpno(Integer empno) {
        this.empno = empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clbx.gsid
     *
     * @return the value of clbx.gsid
     *
     * @mbg.generated
     */
    public Integer getGsid() {
        return gsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clbx.gsid
     *
     * @param gsid the value for clbx.gsid
     *
     * @mbg.generated
     */
    public void setGsid(Integer gsid) {
        this.gsid = gsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clbx.cusid
     *
     * @return the value of clbx.cusid
     *
     * @mbg.generated
     */
    public Integer getCusid() {
        return cusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clbx.cusid
     *
     * @param cusid the value for clbx.cusid
     *
     * @mbg.generated
     */
    public void setCusid(Integer cusid) {
        this.cusid = cusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clbx.bxdh
     *
     * @return the value of clbx.bxdh
     *
     * @mbg.generated
     */
    public String getBxdh() {
        return bxdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clbx.bxdh
     *
     * @param bxdh the value for clbx.bxdh
     *
     * @mbg.generated
     */
    public void setBxdh(String bxdh) {
        this.bxdh = bxdh == null ? null : bxdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clbx.bxdate
     *
     * @return the value of clbx.bxdate
     *
     * @mbg.generated
     */
    public Date getBxdate() {
        return bxdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clbx.bxdate
     *
     * @param bxdate the value for clbx.bxdate
     *
     * @mbg.generated
     */
    public void setBxdate(Date bxdate) {
        this.bxdate = bxdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clbx.bxstate
     *
     * @return the value of clbx.bxstate
     *
     * @mbg.generated
     */
    public String getBxstate() {
        return bxstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clbx.bxstate
     *
     * @param bxstate the value for clbx.bxstate
     *
     * @mbg.generated
     */
    public void setBxstate(String bxstate) {
        this.bxstate = bxstate == null ? null : bxstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clbx.bxnum
     *
     * @return the value of clbx.bxnum
     *
     * @mbg.generated
     */
    public Integer getBxnum() {
        return bxnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clbx.bxnum
     *
     * @param bxnum the value for clbx.bxnum
     *
     * @mbg.generated
     */
    public void setBxnum(Integer bxnum) {
        this.bxnum = bxnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clbx.tbdate
     *
     * @return the value of clbx.tbdate
     *
     * @mbg.generated
     */
    public Date getTbdate() {
        return tbdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clbx.tbdate
     *
     * @param tbdate the value for clbx.tbdate
     *
     * @mbg.generated
     */
    public void setTbdate(Date tbdate) {
        this.tbdate = tbdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clbx.dbdate
     *
     * @return the value of clbx.dbdate
     *
     * @mbg.generated
     */
    public Date getDbdate() {
        return dbdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clbx.dbdate
     *
     * @param dbdate the value for clbx.dbdate
     *
     * @mbg.generated
     */
    public void setDbdate(Date dbdate) {
        this.dbdate = dbdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clbx
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", cbxid=").append(cbxid);
        sb.append(", carid=").append(carid);
        sb.append(", empno=").append(empno);
        sb.append(", gsid=").append(gsid);
        sb.append(", cusid=").append(cusid);
        sb.append(", bxdh=").append(bxdh);
        sb.append(", bxdate=").append(bxdate);
        sb.append(", bxstate=").append(bxstate);
        sb.append(", bxnum=").append(bxnum);
        sb.append(", tbdate=").append(tbdate);
        sb.append(", dbdate=").append(dbdate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}