package com.study.pojo;

import java.io.Serializable;
import java.util.Date;

public class Collection implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.coid
     *
     * @mbg.generated
     */
    private Integer coid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.cgid
     *
     * @mbg.generated
     */
    private Integer cgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.copmtype
     *
     * @mbg.generated
     */
    private String copmtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.coremarks
     *
     * @mbg.generated
     */
    private String coremarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.cocredential
     *
     * @mbg.generated
     */
    private String cocredential;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.codate
     *
     * @mbg.generated
     */
    private Date codate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table collection
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.coid
     *
     * @return the value of collection.coid
     *
     * @mbg.generated
     */
    public Integer getCoid() {
        return coid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.coid
     *
     * @param coid the value for collection.coid
     *
     * @mbg.generated
     */
    public void setCoid(Integer coid) {
        this.coid = coid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.cgid
     *
     * @return the value of collection.cgid
     *
     * @mbg.generated
     */
    public Integer getCgid() {
        return cgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.cgid
     *
     * @param cgid the value for collection.cgid
     *
     * @mbg.generated
     */
    public void setCgid(Integer cgid) {
        this.cgid = cgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.copmtype
     *
     * @return the value of collection.copmtype
     *
     * @mbg.generated
     */
    public String getCopmtype() {
        return copmtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.copmtype
     *
     * @param copmtype the value for collection.copmtype
     *
     * @mbg.generated
     */
    public void setCopmtype(String copmtype) {
        this.copmtype = copmtype == null ? null : copmtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.coremarks
     *
     * @return the value of collection.coremarks
     *
     * @mbg.generated
     */
    public String getCoremarks() {
        return coremarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.coremarks
     *
     * @param coremarks the value for collection.coremarks
     *
     * @mbg.generated
     */
    public void setCoremarks(String coremarks) {
        this.coremarks = coremarks == null ? null : coremarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.cocredential
     *
     * @return the value of collection.cocredential
     *
     * @mbg.generated
     */
    public String getCocredential() {
        return cocredential;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.cocredential
     *
     * @param cocredential the value for collection.cocredential
     *
     * @mbg.generated
     */
    public void setCocredential(String cocredential) {
        this.cocredential = cocredential == null ? null : cocredential.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.codate
     *
     * @return the value of collection.codate
     *
     * @mbg.generated
     */
    public Date getCodate() {
        return codate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.codate
     *
     * @param codate the value for collection.codate
     *
     * @mbg.generated
     */
    public void setCodate(Date codate) {
        this.codate = codate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", coid=").append(coid);
        sb.append(", cgid=").append(cgid);
        sb.append(", copmtype=").append(copmtype);
        sb.append(", coremarks=").append(coremarks);
        sb.append(", cocredential=").append(cocredential);
        sb.append(", codate=").append(codate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}