package com.study.pojo;

import java.io.Serializable;
import java.util.Date;

public class Customer implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cusid
     *
     * @mbg.generated
     */
    private Integer cusid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cstore
     *
     * @mbg.generated
     */
    private Integer cstore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cname
     *
     * @mbg.generated
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.ctel
     *
     * @mbg.generated
     */
    private String ctel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cidcardno
     *
     * @mbg.generated
     */
    private Integer cidcardno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.csex
     *
     * @mbg.generated
     */
    private String csex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cbirth
     *
     * @mbg.generated
     */
    private Date cbirth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.clinkman
     *
     * @mbg.generated
     */
    private String clinkman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.custype
     *
     * @mbg.generated
     */
    private String custype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cuslevel
     *
     * @mbg.generated
     */
    private String cuslevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cbankaccount
     *
     * @mbg.generated
     */
    private String cbankaccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.clasttime
     *
     * @mbg.generated
     */
    private Date clasttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.ccarnum
     *
     * @mbg.generated
     */
    private Integer ccarnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cadress
     *
     * @mbg.generated
     */
    private String cadress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cadvisor
     *
     * @mbg.generated
     */
    private Integer cadvisor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cremark
     *
     * @mbg.generated
     */
    private String cremark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cregtime
     *
     * @mbg.generated
     */
    private Date cregtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cstatus
     *
     * @mbg.generated
     */
    private Integer cstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cusid
     *
     * @return the value of customer.cusid
     *
     * @mbg.generated
     */
    public Integer getCusid() {
        return cusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cusid
     *
     * @param cusid the value for customer.cusid
     *
     * @mbg.generated
     */
    public void setCusid(Integer cusid) {
        this.cusid = cusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cstore
     *
     * @return the value of customer.cstore
     *
     * @mbg.generated
     */
    public Integer getCstore() {
        return cstore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cstore
     *
     * @param cstore the value for customer.cstore
     *
     * @mbg.generated
     */
    public void setCstore(Integer cstore) {
        this.cstore = cstore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cname
     *
     * @return the value of customer.cname
     *
     * @mbg.generated
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cname
     *
     * @param cname the value for customer.cname
     *
     * @mbg.generated
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.ctel
     *
     * @return the value of customer.ctel
     *
     * @mbg.generated
     */
    public String getCtel() {
        return ctel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.ctel
     *
     * @param ctel the value for customer.ctel
     *
     * @mbg.generated
     */
    public void setCtel(String ctel) {
        this.ctel = ctel == null ? null : ctel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cidcardno
     *
     * @return the value of customer.cidcardno
     *
     * @mbg.generated
     */
    public Integer getCidcardno() {
        return cidcardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cidcardno
     *
     * @param cidcardno the value for customer.cidcardno
     *
     * @mbg.generated
     */
    public void setCidcardno(Integer cidcardno) {
        this.cidcardno = cidcardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.csex
     *
     * @return the value of customer.csex
     *
     * @mbg.generated
     */
    public String getCsex() {
        return csex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.csex
     *
     * @param csex the value for customer.csex
     *
     * @mbg.generated
     */
    public void setCsex(String csex) {
        this.csex = csex == null ? null : csex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cbirth
     *
     * @return the value of customer.cbirth
     *
     * @mbg.generated
     */
    public Date getCbirth() {
        return cbirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cbirth
     *
     * @param cbirth the value for customer.cbirth
     *
     * @mbg.generated
     */
    public void setCbirth(Date cbirth) {
        this.cbirth = cbirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.clinkman
     *
     * @return the value of customer.clinkman
     *
     * @mbg.generated
     */
    public String getClinkman() {
        return clinkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.clinkman
     *
     * @param clinkman the value for customer.clinkman
     *
     * @mbg.generated
     */
    public void setClinkman(String clinkman) {
        this.clinkman = clinkman == null ? null : clinkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.custype
     *
     * @return the value of customer.custype
     *
     * @mbg.generated
     */
    public String getCustype() {
        return custype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.custype
     *
     * @param custype the value for customer.custype
     *
     * @mbg.generated
     */
    public void setCustype(String custype) {
        this.custype = custype == null ? null : custype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cuslevel
     *
     * @return the value of customer.cuslevel
     *
     * @mbg.generated
     */
    public String getCuslevel() {
        return cuslevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cuslevel
     *
     * @param cuslevel the value for customer.cuslevel
     *
     * @mbg.generated
     */
    public void setCuslevel(String cuslevel) {
        this.cuslevel = cuslevel == null ? null : cuslevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cbankaccount
     *
     * @return the value of customer.cbankaccount
     *
     * @mbg.generated
     */
    public String getCbankaccount() {
        return cbankaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cbankaccount
     *
     * @param cbankaccount the value for customer.cbankaccount
     *
     * @mbg.generated
     */
    public void setCbankaccount(String cbankaccount) {
        this.cbankaccount = cbankaccount == null ? null : cbankaccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.clasttime
     *
     * @return the value of customer.clasttime
     *
     * @mbg.generated
     */
    public Date getClasttime() {
        return clasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.clasttime
     *
     * @param clasttime the value for customer.clasttime
     *
     * @mbg.generated
     */
    public void setClasttime(Date clasttime) {
        this.clasttime = clasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.ccarnum
     *
     * @return the value of customer.ccarnum
     *
     * @mbg.generated
     */
    public Integer getCcarnum() {
        return ccarnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.ccarnum
     *
     * @param ccarnum the value for customer.ccarnum
     *
     * @mbg.generated
     */
    public void setCcarnum(Integer ccarnum) {
        this.ccarnum = ccarnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cadress
     *
     * @return the value of customer.cadress
     *
     * @mbg.generated
     */
    public String getCadress() {
        return cadress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cadress
     *
     * @param cadress the value for customer.cadress
     *
     * @mbg.generated
     */
    public void setCadress(String cadress) {
        this.cadress = cadress == null ? null : cadress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cadvisor
     *
     * @return the value of customer.cadvisor
     *
     * @mbg.generated
     */
    public Integer getCadvisor() {
        return cadvisor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cadvisor
     *
     * @param cadvisor the value for customer.cadvisor
     *
     * @mbg.generated
     */
    public void setCadvisor(Integer cadvisor) {
        this.cadvisor = cadvisor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cremark
     *
     * @return the value of customer.cremark
     *
     * @mbg.generated
     */
    public String getCremark() {
        return cremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cremark
     *
     * @param cremark the value for customer.cremark
     *
     * @mbg.generated
     */
    public void setCremark(String cremark) {
        this.cremark = cremark == null ? null : cremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cregtime
     *
     * @return the value of customer.cregtime
     *
     * @mbg.generated
     */
    public Date getCregtime() {
        return cregtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cregtime
     *
     * @param cregtime the value for customer.cregtime
     *
     * @mbg.generated
     */
    public void setCregtime(Date cregtime) {
        this.cregtime = cregtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cstatus
     *
     * @return the value of customer.cstatus
     *
     * @mbg.generated
     */
    public Integer getCstatus() {
        return cstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cstatus
     *
     * @param cstatus the value for customer.cstatus
     *
     * @mbg.generated
     */
    public void setCstatus(Integer cstatus) {
        this.cstatus = cstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", cusid=").append(cusid);
        sb.append(", cstore=").append(cstore);
        sb.append(", cname=").append(cname);
        sb.append(", ctel=").append(ctel);
        sb.append(", cidcardno=").append(cidcardno);
        sb.append(", csex=").append(csex);
        sb.append(", cbirth=").append(cbirth);
        sb.append(", clinkman=").append(clinkman);
        sb.append(", custype=").append(custype);
        sb.append(", cuslevel=").append(cuslevel);
        sb.append(", cbankaccount=").append(cbankaccount);
        sb.append(", clasttime=").append(clasttime);
        sb.append(", ccarnum=").append(ccarnum);
        sb.append(", cadress=").append(cadress);
        sb.append(", cadvisor=").append(cadvisor);
        sb.append(", cremark=").append(cremark);
        sb.append(", cregtime=").append(cregtime);
        sb.append(", cstatus=").append(cstatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}