package com.study.pojo;

import java.io.Serializable;
import java.util.Date;

public class Dbfuwu implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbfuwu.dfid
     *
     * @mbg.generated
     */
    private Integer dfid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbfuwu.fwid
     *
     * @mbg.generated
     */
    private Integer fwid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbfuwu.cusid
     *
     * @mbg.generated
     */
    private Integer cusid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbfuwu.empno
     *
     * @mbg.generated
     */
    private Integer empno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbfuwu.dfdh
     *
     * @mbg.generated
     */
    private String dfdh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbfuwu.dbcreatetime
     *
     * @mbg.generated
     */
    private Date dbcreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbfuwu.dbtype
     *
     * @mbg.generated
     */
    private String dbtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbfuwu
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbfuwu.dfid
     *
     * @return the value of dbfuwu.dfid
     *
     * @mbg.generated
     */
    public Integer getDfid() {
        return dfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbfuwu.dfid
     *
     * @param dfid the value for dbfuwu.dfid
     *
     * @mbg.generated
     */
    public void setDfid(Integer dfid) {
        this.dfid = dfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbfuwu.fwid
     *
     * @return the value of dbfuwu.fwid
     *
     * @mbg.generated
     */
    public Integer getFwid() {
        return fwid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbfuwu.fwid
     *
     * @param fwid the value for dbfuwu.fwid
     *
     * @mbg.generated
     */
    public void setFwid(Integer fwid) {
        this.fwid = fwid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbfuwu.cusid
     *
     * @return the value of dbfuwu.cusid
     *
     * @mbg.generated
     */
    public Integer getCusid() {
        return cusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbfuwu.cusid
     *
     * @param cusid the value for dbfuwu.cusid
     *
     * @mbg.generated
     */
    public void setCusid(Integer cusid) {
        this.cusid = cusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbfuwu.empno
     *
     * @return the value of dbfuwu.empno
     *
     * @mbg.generated
     */
    public Integer getEmpno() {
        return empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbfuwu.empno
     *
     * @param empno the value for dbfuwu.empno
     *
     * @mbg.generated
     */
    public void setEmpno(Integer empno) {
        this.empno = empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbfuwu.dfdh
     *
     * @return the value of dbfuwu.dfdh
     *
     * @mbg.generated
     */
    public String getDfdh() {
        return dfdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbfuwu.dfdh
     *
     * @param dfdh the value for dbfuwu.dfdh
     *
     * @mbg.generated
     */
    public void setDfdh(String dfdh) {
        this.dfdh = dfdh == null ? null : dfdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbfuwu.dbcreatetime
     *
     * @return the value of dbfuwu.dbcreatetime
     *
     * @mbg.generated
     */
    public Date getDbcreatetime() {
        return dbcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbfuwu.dbcreatetime
     *
     * @param dbcreatetime the value for dbfuwu.dbcreatetime
     *
     * @mbg.generated
     */
    public void setDbcreatetime(Date dbcreatetime) {
        this.dbcreatetime = dbcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbfuwu.dbtype
     *
     * @return the value of dbfuwu.dbtype
     *
     * @mbg.generated
     */
    public String getDbtype() {
        return dbtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbfuwu.dbtype
     *
     * @param dbtype the value for dbfuwu.dbtype
     *
     * @mbg.generated
     */
    public void setDbtype(String dbtype) {
        this.dbtype = dbtype == null ? null : dbtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbfuwu
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", dfid=").append(dfid);
        sb.append(", fwid=").append(fwid);
        sb.append(", cusid=").append(cusid);
        sb.append(", empno=").append(empno);
        sb.append(", dfdh=").append(dfdh);
        sb.append(", dbcreatetime=").append(dbcreatetime);
        sb.append(", dbtype=").append(dbtype);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}