package com.study.pojo;

import java.io.Serializable;
import java.util.Date;

public class Debitnote implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column debitnote.dnid
     *
     * @mbg.generated
     */
    private Integer dnid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column debitnote.inid
     *
     * @mbg.generated
     */
    private Integer inid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column debitnote.rid
     *
     * @mbg.generated
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column debitnote.dnpmtype
     *
     * @mbg.generated
     */
    private String dnpmtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column debitnote.dnremarks
     *
     * @mbg.generated
     */
    private String dnremarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column debitnote.dncredential
     *
     * @mbg.generated
     */
    private String dncredential;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column debitnote.dntime
     *
     * @mbg.generated
     */
    private Date dntime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table debitnote
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column debitnote.dnid
     *
     * @return the value of debitnote.dnid
     *
     * @mbg.generated
     */
    public Integer getDnid() {
        return dnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column debitnote.dnid
     *
     * @param dnid the value for debitnote.dnid
     *
     * @mbg.generated
     */
    public void setDnid(Integer dnid) {
        this.dnid = dnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column debitnote.inid
     *
     * @return the value of debitnote.inid
     *
     * @mbg.generated
     */
    public Integer getInid() {
        return inid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column debitnote.inid
     *
     * @param inid the value for debitnote.inid
     *
     * @mbg.generated
     */
    public void setInid(Integer inid) {
        this.inid = inid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column debitnote.rid
     *
     * @return the value of debitnote.rid
     *
     * @mbg.generated
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column debitnote.rid
     *
     * @param rid the value for debitnote.rid
     *
     * @mbg.generated
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column debitnote.dnpmtype
     *
     * @return the value of debitnote.dnpmtype
     *
     * @mbg.generated
     */
    public String getDnpmtype() {
        return dnpmtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column debitnote.dnpmtype
     *
     * @param dnpmtype the value for debitnote.dnpmtype
     *
     * @mbg.generated
     */
    public void setDnpmtype(String dnpmtype) {
        this.dnpmtype = dnpmtype == null ? null : dnpmtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column debitnote.dnremarks
     *
     * @return the value of debitnote.dnremarks
     *
     * @mbg.generated
     */
    public String getDnremarks() {
        return dnremarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column debitnote.dnremarks
     *
     * @param dnremarks the value for debitnote.dnremarks
     *
     * @mbg.generated
     */
    public void setDnremarks(String dnremarks) {
        this.dnremarks = dnremarks == null ? null : dnremarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column debitnote.dncredential
     *
     * @return the value of debitnote.dncredential
     *
     * @mbg.generated
     */
    public String getDncredential() {
        return dncredential;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column debitnote.dncredential
     *
     * @param dncredential the value for debitnote.dncredential
     *
     * @mbg.generated
     */
    public void setDncredential(String dncredential) {
        this.dncredential = dncredential == null ? null : dncredential.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column debitnote.dntime
     *
     * @return the value of debitnote.dntime
     *
     * @mbg.generated
     */
    public Date getDntime() {
        return dntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column debitnote.dntime
     *
     * @param dntime the value for debitnote.dntime
     *
     * @mbg.generated
     */
    public void setDntime(Date dntime) {
        this.dntime = dntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debitnote
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", dnid=").append(dnid);
        sb.append(", inid=").append(inid);
        sb.append(", rid=").append(rid);
        sb.append(", dnpmtype=").append(dnpmtype);
        sb.append(", dnremarks=").append(dnremarks);
        sb.append(", dncredential=").append(dncredential);
        sb.append(", dntime=").append(dntime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}