package com.study.pojo;

import java.io.Serializable;

public class Emp implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.empno
     *
     * @mbg.generated
     */
    private Integer empno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.deptno
     *
     * @mbg.generated
     */
    private Integer deptno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.ename
     *
     * @mbg.generated
     */
    private String ename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.ephone
     *
     * @mbg.generated
     */
    private Long ephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.shangji
     *
     * @mbg.generated
     */
    private Integer shangji;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.estart
     *
     * @mbg.generated
     */
    private String estart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table emp
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.empno
     *
     * @return the value of emp.empno
     *
     * @mbg.generated
     */
    public Integer getEmpno() {
        return empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.empno
     *
     * @param empno the value for emp.empno
     *
     * @mbg.generated
     */
    public void setEmpno(Integer empno) {
        this.empno = empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.deptno
     *
     * @return the value of emp.deptno
     *
     * @mbg.generated
     */
    public Integer getDeptno() {
        return deptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.deptno
     *
     * @param deptno the value for emp.deptno
     *
     * @mbg.generated
     */
    public void setDeptno(Integer deptno) {
        this.deptno = deptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.ename
     *
     * @return the value of emp.ename
     *
     * @mbg.generated
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.ename
     *
     * @param ename the value for emp.ename
     *
     * @mbg.generated
     */
    public void setEname(String ename) {
        this.ename = ename == null ? null : ename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.ephone
     *
     * @return the value of emp.ephone
     *
     * @mbg.generated
     */
    public Long getEphone() {
        return ephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.ephone
     *
     * @param ephone the value for emp.ephone
     *
     * @mbg.generated
     */
    public void setEphone(Long ephone) {
        this.ephone = ephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.shangji
     *
     * @return the value of emp.shangji
     *
     * @mbg.generated
     */
    public Integer getShangji() {
        return shangji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.shangji
     *
     * @param shangji the value for emp.shangji
     *
     * @mbg.generated
     */
    public void setShangji(Integer shangji) {
        this.shangji = shangji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.sex
     *
     * @return the value of emp.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.sex
     *
     * @param sex the value for emp.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.estart
     *
     * @return the value of emp.estart
     *
     * @mbg.generated
     */
    public String getEstart() {
        return estart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.estart
     *
     * @param estart the value for emp.estart
     *
     * @mbg.generated
     */
    public void setEstart(String estart) {
        this.estart = estart == null ? null : estart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", empno=").append(empno);
        sb.append(", deptno=").append(deptno);
        sb.append(", ename=").append(ename);
        sb.append(", ephone=").append(ephone);
        sb.append(", shangji=").append(shangji);
        sb.append(", sex=").append(sex);
        sb.append(", estart=").append(estart);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}