package com.study.pojo;

import java.io.Serializable;

public class Fuwu implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fuwu.fwid
     *
     * @mbg.generated
     */
    private Integer fwid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fuwu.bwid
     *
     * @mbg.generated
     */
    private Integer bwid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fuwu.fwflid
     *
     * @mbg.generated
     */
    private Integer fwflid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fuwu.fwcoding
     *
     * @mbg.generated
     */
    private String fwcoding;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fuwu.fwname
     *
     * @mbg.generated
     */
    private String fwname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fuwu.duration
     *
     * @mbg.generated
     */
    private Integer duration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fuwu.fwjia
     *
     * @mbg.generated
     */
    private Float fwjia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fuwu.dfbeizhu
     *
     * @mbg.generated
     */
    private String dfbeizhu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fuwu.fwstart
     *
     * @mbg.generated
     */
    private String fwstart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fuwu
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fuwu.fwid
     *
     * @return the value of fuwu.fwid
     *
     * @mbg.generated
     */
    public Integer getFwid() {
        return fwid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fuwu.fwid
     *
     * @param fwid the value for fuwu.fwid
     *
     * @mbg.generated
     */
    public void setFwid(Integer fwid) {
        this.fwid = fwid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fuwu.bwid
     *
     * @return the value of fuwu.bwid
     *
     * @mbg.generated
     */
    public Integer getBwid() {
        return bwid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fuwu.bwid
     *
     * @param bwid the value for fuwu.bwid
     *
     * @mbg.generated
     */
    public void setBwid(Integer bwid) {
        this.bwid = bwid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fuwu.fwflid
     *
     * @return the value of fuwu.fwflid
     *
     * @mbg.generated
     */
    public Integer getFwflid() {
        return fwflid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fuwu.fwflid
     *
     * @param fwflid the value for fuwu.fwflid
     *
     * @mbg.generated
     */
    public void setFwflid(Integer fwflid) {
        this.fwflid = fwflid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fuwu.fwcoding
     *
     * @return the value of fuwu.fwcoding
     *
     * @mbg.generated
     */
    public String getFwcoding() {
        return fwcoding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fuwu.fwcoding
     *
     * @param fwcoding the value for fuwu.fwcoding
     *
     * @mbg.generated
     */
    public void setFwcoding(String fwcoding) {
        this.fwcoding = fwcoding == null ? null : fwcoding.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fuwu.fwname
     *
     * @return the value of fuwu.fwname
     *
     * @mbg.generated
     */
    public String getFwname() {
        return fwname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fuwu.fwname
     *
     * @param fwname the value for fuwu.fwname
     *
     * @mbg.generated
     */
    public void setFwname(String fwname) {
        this.fwname = fwname == null ? null : fwname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fuwu.duration
     *
     * @return the value of fuwu.duration
     *
     * @mbg.generated
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fuwu.duration
     *
     * @param duration the value for fuwu.duration
     *
     * @mbg.generated
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fuwu.fwjia
     *
     * @return the value of fuwu.fwjia
     *
     * @mbg.generated
     */
    public Float getFwjia() {
        return fwjia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fuwu.fwjia
     *
     * @param fwjia the value for fuwu.fwjia
     *
     * @mbg.generated
     */
    public void setFwjia(Float fwjia) {
        this.fwjia = fwjia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fuwu.dfbeizhu
     *
     * @return the value of fuwu.dfbeizhu
     *
     * @mbg.generated
     */
    public String getDfbeizhu() {
        return dfbeizhu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fuwu.dfbeizhu
     *
     * @param dfbeizhu the value for fuwu.dfbeizhu
     *
     * @mbg.generated
     */
    public void setDfbeizhu(String dfbeizhu) {
        this.dfbeizhu = dfbeizhu == null ? null : dfbeizhu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fuwu.fwstart
     *
     * @return the value of fuwu.fwstart
     *
     * @mbg.generated
     */
    public String getFwstart() {
        return fwstart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fuwu.fwstart
     *
     * @param fwstart the value for fuwu.fwstart
     *
     * @mbg.generated
     */
    public void setFwstart(String fwstart) {
        this.fwstart = fwstart == null ? null : fwstart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fuwu
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", fwid=").append(fwid);
        sb.append(", bwid=").append(bwid);
        sb.append(", fwflid=").append(fwflid);
        sb.append(", fwcoding=").append(fwcoding);
        sb.append(", fwname=").append(fwname);
        sb.append(", duration=").append(duration);
        sb.append(", fwjia=").append(fwjia);
        sb.append(", dfbeizhu=").append(dfbeizhu);
        sb.append(", fwstart=").append(fwstart);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}