package com.study.pojo;

import java.io.Serializable;

public class Fwleibie implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwleibie.fwflid
     *
     * @mbg.generated
     */
    private Integer fwflid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwleibie.fwflname
     *
     * @mbg.generated
     */
    private String fwflname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwleibie.fwflstart
     *
     * @mbg.generated
     */
    private String fwflstart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fwleibie
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwleibie.fwflid
     *
     * @return the value of fwleibie.fwflid
     *
     * @mbg.generated
     */
    public Integer getFwflid() {
        return fwflid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwleibie.fwflid
     *
     * @param fwflid the value for fwleibie.fwflid
     *
     * @mbg.generated
     */
    public void setFwflid(Integer fwflid) {
        this.fwflid = fwflid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwleibie.fwflname
     *
     * @return the value of fwleibie.fwflname
     *
     * @mbg.generated
     */
    public String getFwflname() {
        return fwflname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwleibie.fwflname
     *
     * @param fwflname the value for fwleibie.fwflname
     *
     * @mbg.generated
     */
    public void setFwflname(String fwflname) {
        this.fwflname = fwflname == null ? null : fwflname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwleibie.fwflstart
     *
     * @return the value of fwleibie.fwflstart
     *
     * @mbg.generated
     */
    public String getFwflstart() {
        return fwflstart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwleibie.fwflstart
     *
     * @param fwflstart the value for fwleibie.fwflstart
     *
     * @mbg.generated
     */
    public void setFwflstart(String fwflstart) {
        this.fwflstart = fwflstart == null ? null : fwflstart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwleibie
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", fwflid=").append(fwflid);
        sb.append(", fwflname=").append(fwflname);
        sb.append(", fwflstart=").append(fwflstart);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}