package com.study.pojo;

import java.io.Serializable;

public class Gongsi implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gongsi.gsid
     *
     * @mbg.generated
     */
    private Integer gsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gongsi.gscoding
     *
     * @mbg.generated
     */
    private String gscoding;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gongsi.gsname
     *
     * @mbg.generated
     */
    private String gsname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gongsi.lxrname
     *
     * @mbg.generated
     */
    private String lxrname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gongsi.lxphone
     *
     * @mbg.generated
     */
    private Long lxphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gongsi.gsbeizhu
     *
     * @mbg.generated
     */
    private String gsbeizhu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gongsi.gsstart
     *
     * @mbg.generated
     */
    private String gsstart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gongsi
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gongsi.gsid
     *
     * @return the value of gongsi.gsid
     *
     * @mbg.generated
     */
    public Integer getGsid() {
        return gsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gongsi.gsid
     *
     * @param gsid the value for gongsi.gsid
     *
     * @mbg.generated
     */
    public void setGsid(Integer gsid) {
        this.gsid = gsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gongsi.gscoding
     *
     * @return the value of gongsi.gscoding
     *
     * @mbg.generated
     */
    public String getGscoding() {
        return gscoding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gongsi.gscoding
     *
     * @param gscoding the value for gongsi.gscoding
     *
     * @mbg.generated
     */
    public void setGscoding(String gscoding) {
        this.gscoding = gscoding == null ? null : gscoding.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gongsi.gsname
     *
     * @return the value of gongsi.gsname
     *
     * @mbg.generated
     */
    public String getGsname() {
        return gsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gongsi.gsname
     *
     * @param gsname the value for gongsi.gsname
     *
     * @mbg.generated
     */
    public void setGsname(String gsname) {
        this.gsname = gsname == null ? null : gsname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gongsi.lxrname
     *
     * @return the value of gongsi.lxrname
     *
     * @mbg.generated
     */
    public String getLxrname() {
        return lxrname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gongsi.lxrname
     *
     * @param lxrname the value for gongsi.lxrname
     *
     * @mbg.generated
     */
    public void setLxrname(String lxrname) {
        this.lxrname = lxrname == null ? null : lxrname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gongsi.lxphone
     *
     * @return the value of gongsi.lxphone
     *
     * @mbg.generated
     */
    public Long getLxphone() {
        return lxphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gongsi.lxphone
     *
     * @param lxphone the value for gongsi.lxphone
     *
     * @mbg.generated
     */
    public void setLxphone(Long lxphone) {
        this.lxphone = lxphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gongsi.gsbeizhu
     *
     * @return the value of gongsi.gsbeizhu
     *
     * @mbg.generated
     */
    public String getGsbeizhu() {
        return gsbeizhu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gongsi.gsbeizhu
     *
     * @param gsbeizhu the value for gongsi.gsbeizhu
     *
     * @mbg.generated
     */
    public void setGsbeizhu(String gsbeizhu) {
        this.gsbeizhu = gsbeizhu == null ? null : gsbeizhu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gongsi.gsstart
     *
     * @return the value of gongsi.gsstart
     *
     * @mbg.generated
     */
    public String getGsstart() {
        return gsstart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gongsi.gsstart
     *
     * @param gsstart the value for gongsi.gsstart
     *
     * @mbg.generated
     */
    public void setGsstart(String gsstart) {
        this.gsstart = gsstart == null ? null : gsstart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongsi
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", gsid=").append(gsid);
        sb.append(", gscoding=").append(gscoding);
        sb.append(", gsname=").append(gsname);
        sb.append(", lxrname=").append(lxrname);
        sb.append(", lxphone=").append(lxphone);
        sb.append(", gsbeizhu=").append(gsbeizhu);
        sb.append(", gsstart=").append(gsstart);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}