package com.study.pojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Invoice implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.inid
     *
     * @mbg.generated
     */
    private Integer inid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.dnid
     *
     * @mbg.generated
     */
    private Integer dnid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.innumber
     *
     * @mbg.generated
     */
    private String innumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.inmoney
     *
     * @mbg.generated
     */
    private BigDecimal inmoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.inremarks
     *
     * @mbg.generated
     */
    private String inremarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.indate
     *
     * @mbg.generated
     */
    private Date indate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table invoice
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.inid
     *
     * @return the value of invoice.inid
     *
     * @mbg.generated
     */
    public Integer getInid() {
        return inid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.inid
     *
     * @param inid the value for invoice.inid
     *
     * @mbg.generated
     */
    public void setInid(Integer inid) {
        this.inid = inid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.dnid
     *
     * @return the value of invoice.dnid
     *
     * @mbg.generated
     */
    public Integer getDnid() {
        return dnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.dnid
     *
     * @param dnid the value for invoice.dnid
     *
     * @mbg.generated
     */
    public void setDnid(Integer dnid) {
        this.dnid = dnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.innumber
     *
     * @return the value of invoice.innumber
     *
     * @mbg.generated
     */
    public String getInnumber() {
        return innumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.innumber
     *
     * @param innumber the value for invoice.innumber
     *
     * @mbg.generated
     */
    public void setInnumber(String innumber) {
        this.innumber = innumber == null ? null : innumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.inmoney
     *
     * @return the value of invoice.inmoney
     *
     * @mbg.generated
     */
    public BigDecimal getInmoney() {
        return inmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.inmoney
     *
     * @param inmoney the value for invoice.inmoney
     *
     * @mbg.generated
     */
    public void setInmoney(BigDecimal inmoney) {
        this.inmoney = inmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.inremarks
     *
     * @return the value of invoice.inremarks
     *
     * @mbg.generated
     */
    public String getInremarks() {
        return inremarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.inremarks
     *
     * @param inremarks the value for invoice.inremarks
     *
     * @mbg.generated
     */
    public void setInremarks(String inremarks) {
        this.inremarks = inremarks == null ? null : inremarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.indate
     *
     * @return the value of invoice.indate
     *
     * @mbg.generated
     */
    public Date getIndate() {
        return indate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.indate
     *
     * @param indate the value for invoice.indate
     *
     * @mbg.generated
     */
    public void setIndate(Date indate) {
        this.indate = indate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", inid=").append(inid);
        sb.append(", dnid=").append(dnid);
        sb.append(", innumber=").append(innumber);
        sb.append(", inmoney=").append(inmoney);
        sb.append(", inremarks=").append(inremarks);
        sb.append(", indate=").append(indate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}