package com.study.pojo;

import java.io.Serializable;

public class Pinpai implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pinpai.ppid
     *
     * @mbg.generated
     */
    private Integer ppid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pinpai.ppname
     *
     * @mbg.generated
     */
    private String ppname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pinpai.ppstart
     *
     * @mbg.generated
     */
    private String ppstart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pinpai
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pinpai.ppid
     *
     * @return the value of pinpai.ppid
     *
     * @mbg.generated
     */
    public Integer getPpid() {
        return ppid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pinpai.ppid
     *
     * @param ppid the value for pinpai.ppid
     *
     * @mbg.generated
     */
    public void setPpid(Integer ppid) {
        this.ppid = ppid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pinpai.ppname
     *
     * @return the value of pinpai.ppname
     *
     * @mbg.generated
     */
    public String getPpname() {
        return ppname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pinpai.ppname
     *
     * @param ppname the value for pinpai.ppname
     *
     * @mbg.generated
     */
    public void setPpname(String ppname) {
        this.ppname = ppname == null ? null : ppname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pinpai.ppstart
     *
     * @return the value of pinpai.ppstart
     *
     * @mbg.generated
     */
    public String getPpstart() {
        return ppstart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pinpai.ppstart
     *
     * @param ppstart the value for pinpai.ppstart
     *
     * @mbg.generated
     */
    public void setPpstart(String ppstart) {
        this.ppstart = ppstart == null ? null : ppstart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pinpai
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ppid=").append(ppid);
        sb.append(", ppname=").append(ppname);
        sb.append(", ppstart=").append(ppstart);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}