package com.study.pojo;

import java.io.Serializable;

public class Store implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.storeid
     *
     * @mbg.generated
     */
    private Integer storeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.storename
     *
     * @mbg.generated
     */
    private String storename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.storefullname
     *
     * @mbg.generated
     */
    private String storefullname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.storeleader
     *
     * @mbg.generated
     */
    private Integer storeleader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.storeqq
     *
     * @mbg.generated
     */
    private String storeqq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.storetel
     *
     * @mbg.generated
     */
    private String storetel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.storeadress
     *
     * @mbg.generated
     */
    private String storeadress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.storestatus
     *
     * @mbg.generated
     */
    private Integer storestatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table store
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.storeid
     *
     * @return the value of store.storeid
     *
     * @mbg.generated
     */
    public Integer getStoreid() {
        return storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.storeid
     *
     * @param storeid the value for store.storeid
     *
     * @mbg.generated
     */
    public void setStoreid(Integer storeid) {
        this.storeid = storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.storename
     *
     * @return the value of store.storename
     *
     * @mbg.generated
     */
    public String getStorename() {
        return storename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.storename
     *
     * @param storename the value for store.storename
     *
     * @mbg.generated
     */
    public void setStorename(String storename) {
        this.storename = storename == null ? null : storename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.storefullname
     *
     * @return the value of store.storefullname
     *
     * @mbg.generated
     */
    public String getStorefullname() {
        return storefullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.storefullname
     *
     * @param storefullname the value for store.storefullname
     *
     * @mbg.generated
     */
    public void setStorefullname(String storefullname) {
        this.storefullname = storefullname == null ? null : storefullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.storeleader
     *
     * @return the value of store.storeleader
     *
     * @mbg.generated
     */
    public Integer getStoreleader() {
        return storeleader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.storeleader
     *
     * @param storeleader the value for store.storeleader
     *
     * @mbg.generated
     */
    public void setStoreleader(Integer storeleader) {
        this.storeleader = storeleader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.storeqq
     *
     * @return the value of store.storeqq
     *
     * @mbg.generated
     */
    public String getStoreqq() {
        return storeqq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.storeqq
     *
     * @param storeqq the value for store.storeqq
     *
     * @mbg.generated
     */
    public void setStoreqq(String storeqq) {
        this.storeqq = storeqq == null ? null : storeqq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.storetel
     *
     * @return the value of store.storetel
     *
     * @mbg.generated
     */
    public String getStoretel() {
        return storetel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.storetel
     *
     * @param storetel the value for store.storetel
     *
     * @mbg.generated
     */
    public void setStoretel(String storetel) {
        this.storetel = storetel == null ? null : storetel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.storeadress
     *
     * @return the value of store.storeadress
     *
     * @mbg.generated
     */
    public String getStoreadress() {
        return storeadress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.storeadress
     *
     * @param storeadress the value for store.storeadress
     *
     * @mbg.generated
     */
    public void setStoreadress(String storeadress) {
        this.storeadress = storeadress == null ? null : storeadress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.storestatus
     *
     * @return the value of store.storestatus
     *
     * @mbg.generated
     */
    public Integer getStorestatus() {
        return storestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.storestatus
     *
     * @param storestatus the value for store.storestatus
     *
     * @mbg.generated
     */
    public void setStorestatus(Integer storestatus) {
        this.storestatus = storestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", storeid=").append(storeid);
        sb.append(", storename=").append(storename);
        sb.append(", storefullname=").append(storefullname);
        sb.append(", storeleader=").append(storeleader);
        sb.append(", storeqq=").append(storeqq);
        sb.append(", storetel=").append(storetel);
        sb.append(", storeadress=").append(storeadress);
        sb.append(", storestatus=").append(storestatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}