package com.study.pojo;

import java.io.Serializable;

public class Supplier implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.sid2
     *
     * @mbg.generated
     */
    private Integer sid2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.sgysname
     *
     * @mbg.generated
     */
    private String sgysname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.stype
     *
     * @mbg.generated
     */
    private String stype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.snum
     *
     * @mbg.generated
     */
    private String snum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.sname
     *
     * @mbg.generated
     */
    private String sname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.sphone
     *
     * @mbg.generated
     */
    private Long sphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table supplier
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.sid2
     *
     * @return the value of supplier.sid2
     *
     * @mbg.generated
     */
    public Integer getSid2() {
        return sid2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.sid2
     *
     * @param sid2 the value for supplier.sid2
     *
     * @mbg.generated
     */
    public void setSid2(Integer sid2) {
        this.sid2 = sid2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.sgysname
     *
     * @return the value of supplier.sgysname
     *
     * @mbg.generated
     */
    public String getSgysname() {
        return sgysname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.sgysname
     *
     * @param sgysname the value for supplier.sgysname
     *
     * @mbg.generated
     */
    public void setSgysname(String sgysname) {
        this.sgysname = sgysname == null ? null : sgysname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.stype
     *
     * @return the value of supplier.stype
     *
     * @mbg.generated
     */
    public String getStype() {
        return stype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.stype
     *
     * @param stype the value for supplier.stype
     *
     * @mbg.generated
     */
    public void setStype(String stype) {
        this.stype = stype == null ? null : stype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.snum
     *
     * @return the value of supplier.snum
     *
     * @mbg.generated
     */
    public String getSnum() {
        return snum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.snum
     *
     * @param snum the value for supplier.snum
     *
     * @mbg.generated
     */
    public void setSnum(String snum) {
        this.snum = snum == null ? null : snum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.sname
     *
     * @return the value of supplier.sname
     *
     * @mbg.generated
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.sname
     *
     * @param sname the value for supplier.sname
     *
     * @mbg.generated
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.sphone
     *
     * @return the value of supplier.sphone
     *
     * @mbg.generated
     */
    public Long getSphone() {
        return sphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.sphone
     *
     * @param sphone the value for supplier.sphone
     *
     * @mbg.generated
     */
    public void setSphone(Long sphone) {
        this.sphone = sphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sid2=").append(sid2);
        sb.append(", sgysname=").append(sgysname);
        sb.append(", stype=").append(stype);
        sb.append(", snum=").append(snum);
        sb.append(", sname=").append(sname);
        sb.append(", sphone=").append(sphone);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}