package com.study.pojo;

import java.io.Serializable;
import java.util.Date;

public class Ypxs implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypxs.xsid
     *
     * @mbg.generated
     */
    private Integer xsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypxs.empno
     *
     * @mbg.generated
     */
    private Integer empno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypxs.ckid
     *
     * @mbg.generated
     */
    private Integer ckid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypxs.cusid
     *
     * @mbg.generated
     */
    private Integer cusid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypxs.xsdh
     *
     * @mbg.generated
     */
    private String xsdh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypxs.xstate
     *
     * @mbg.generated
     */
    private String xstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypxs.xsnum
     *
     * @mbg.generated
     */
    private Integer xsnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypxs.cksta
     *
     * @mbg.generated
     */
    private String cksta;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypxs.xsdate
     *
     * @mbg.generated
     */
    private Date xsdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ypxs
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypxs.xsid
     *
     * @return the value of ypxs.xsid
     *
     * @mbg.generated
     */
    public Integer getXsid() {
        return xsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypxs.xsid
     *
     * @param xsid the value for ypxs.xsid
     *
     * @mbg.generated
     */
    public void setXsid(Integer xsid) {
        this.xsid = xsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypxs.empno
     *
     * @return the value of ypxs.empno
     *
     * @mbg.generated
     */
    public Integer getEmpno() {
        return empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypxs.empno
     *
     * @param empno the value for ypxs.empno
     *
     * @mbg.generated
     */
    public void setEmpno(Integer empno) {
        this.empno = empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypxs.ckid
     *
     * @return the value of ypxs.ckid
     *
     * @mbg.generated
     */
    public Integer getCkid() {
        return ckid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypxs.ckid
     *
     * @param ckid the value for ypxs.ckid
     *
     * @mbg.generated
     */
    public void setCkid(Integer ckid) {
        this.ckid = ckid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypxs.cusid
     *
     * @return the value of ypxs.cusid
     *
     * @mbg.generated
     */
    public Integer getCusid() {
        return cusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypxs.cusid
     *
     * @param cusid the value for ypxs.cusid
     *
     * @mbg.generated
     */
    public void setCusid(Integer cusid) {
        this.cusid = cusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypxs.xsdh
     *
     * @return the value of ypxs.xsdh
     *
     * @mbg.generated
     */
    public String getXsdh() {
        return xsdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypxs.xsdh
     *
     * @param xsdh the value for ypxs.xsdh
     *
     * @mbg.generated
     */
    public void setXsdh(String xsdh) {
        this.xsdh = xsdh == null ? null : xsdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypxs.xstate
     *
     * @return the value of ypxs.xstate
     *
     * @mbg.generated
     */
    public String getXstate() {
        return xstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypxs.xstate
     *
     * @param xstate the value for ypxs.xstate
     *
     * @mbg.generated
     */
    public void setXstate(String xstate) {
        this.xstate = xstate == null ? null : xstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypxs.xsnum
     *
     * @return the value of ypxs.xsnum
     *
     * @mbg.generated
     */
    public Integer getXsnum() {
        return xsnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypxs.xsnum
     *
     * @param xsnum the value for ypxs.xsnum
     *
     * @mbg.generated
     */
    public void setXsnum(Integer xsnum) {
        this.xsnum = xsnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypxs.cksta
     *
     * @return the value of ypxs.cksta
     *
     * @mbg.generated
     */
    public String getCksta() {
        return cksta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypxs.cksta
     *
     * @param cksta the value for ypxs.cksta
     *
     * @mbg.generated
     */
    public void setCksta(String cksta) {
        this.cksta = cksta == null ? null : cksta.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypxs.xsdate
     *
     * @return the value of ypxs.xsdate
     *
     * @mbg.generated
     */
    public Date getXsdate() {
        return xsdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypxs.xsdate
     *
     * @param xsdate the value for ypxs.xsdate
     *
     * @mbg.generated
     */
    public void setXsdate(Date xsdate) {
        this.xsdate = xsdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ypxs
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", xsid=").append(xsid);
        sb.append(", empno=").append(empno);
        sb.append(", ckid=").append(ckid);
        sb.append(", cusid=").append(cusid);
        sb.append(", xsdh=").append(xsdh);
        sb.append(", xstate=").append(xstate);
        sb.append(", xsnum=").append(xsnum);
        sb.append(", cksta=").append(cksta);
        sb.append(", xsdate=").append(xsdate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}